[python]
pyversion = "python3.11"

[config]
test_param = false

[git_paths]
cached_opentims = "git+ssh://git@github.com/michalsta/cached_opentims.git"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
mgf_ops = "git+ssh://git@github.com/midiaIDorg/mgf_ops"
midia_schemes = "git+ssh://git@github.com/midiaIDorg/midia_schemes"
midia_cpp = "git+ssh://git@github.com/midiaIDorg/midia_cpp"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
opentims = "git+ssh://git@github.com/michalsta/opentims"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
paramidiac2 = "git+ssh://git@github.com/midiaIDorg/paramidiac2"
recapuccino = "git+ssh://git@github.com/midiaIDorg/recapuccino"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
snakemaketools = "git+ssh://git@github.com/midiaIDorg/snakemaketools"
midia_fetcher = "git+ssh://git@github.com/midiaIDorg/midia_fetcher"
midia_pipe_hull = "git+ssh://git@github.com/midiaIDorg/midia_pipe_hull"
midia_tester = "git+ssh://git@github.com/midiaIDorg/midia_tester"
tims_tmp = "git+ssh://git@github.com/midiaIDorg/tims_tmp"
seops = "git+ssh://git@github.com/MatteoLacki/seops.git"

[git_versions]
cached_opentims = "a5f24cdc7ca3da0cfcccba72c8f6cff8456084b1"
ClusterMS = "cbfccdbb1f6534fb258bb4d99508fb2775ee8c6e"
dia_common = "32fd9642012afc8b3bca7013b439f67d1c82c2c4"
kilograms = "b9f01a4ac697d92150c51d634007707a03f7ca9f"
mgf_ops = "e027503d5c5c50eeff00308c28b28bd1de48c370"
midia_schemes = "e95807a8d23559f008220f74d36364a2ff9118b4"
midia_cpp = "737ebdf879d9c73bd4501d852fffbade4037d509"
midia_pipe = "57a4044bad473bb037ca6303d7a64f3b69eec9cd"
midia_pipe_hull = "9dc63ba21b63cf73f6ef3c78eab89cfc2982251b"
midia_search_engines = "bbf8dfaef3e9f0cf39a8d2596a047d49d6d15830"
mmapped_df = "181998ab2e92b49f9581babca7aa7f59cd40ddb1"
MSclusterparser = "b7cc866a93cef1bb9d0a07087507cd4e7f501e44"
opentims = "2e9274a62aff350a12d24e45a66123100926e83b"
pandas_ops = "48069f143610e25c94e88c112f73f1f995a6259b"
paramidiac = "efe425c31a4816564753e8c39ece519539b09401"
paramidiac2 = "0fce173ae94b12e368ce2a3acc3bdbe0b410a290"
recapuccino = "6b931ff81d0a461e399ca93749f593831bfc90dd"
savetimspy = "1d89fc43175b7092d56cd02679af9e792985fa55"
snakemaketools = "e251660438aa064653401cfa8105ef4196fe63c0"
midia_fetcher = "099e244d532cc4cc161cb59a55aebe1b33166bf6"
midia_tester = "92cf20e470dfd943bc2726c0da7d7718d3fecdbc"
tims_tmp = "5827533f9c39f23734dceb317a6c4b2183d260c9"
seops = "12b8e6e02abe4e6610d8f871a3b363c8df2b7d9f"

[requirements_external]
agate = "==1.13.0"
agate-dbf = "==0.2.3"
agate-excel = "==0.4.1"
agate-sql = "==0.7.2"
anyio = "==4.8.0"
appdirs = "==1.4.4"
argon2-cffi = "==23.1.0"
argon2-cffi-bindings = "==21.2.0"
argparse-dataclass = "==2.0.0"
arrow = "==1.3.0"
asttokens = "==3.0.0"
async-lru = "==2.0.4"
attrs = "==25.1.0"
babel = "==2.17.0"
beautifulsoup4 = "==4.13.3"
bleach = "==6.2.0"
blosc2 = "==3.2.0"
boto3 = "==1.37.7"
botocore = "==1.37.7"
Brotli = "==1.1.0"
certifi = "==2025.1.31"
cffi = "==1.17.1"
charset-normalizer = "==3.4.1"
click = "==8.1.8"
comm = "==0.2.2"
conda-inject = "==1.3.2"
ConfigArgParse = "==1.7"
connection_pool = "==0.0.3"
contourpy = "==1.3.1"
cramjam = "==2.9.1"
cryptography = "==44.0.2"
csvkit = "==2.1.0"
cycler = "==0.12.1"
Cython = "==3.0.12"
dbfread = "==2.0.7"
debugpy = "==1.8.13"
decorator = "==5.2.1"
defusedxml = "==0.7.1"
docutils = "==0.21.2"
dpath = "==2.2.0"
duckdb = "==1.2.1"
et_xmlfile = "==2.0.0"
executing = "==2.2.0"
fastjsonschema = "==2.21.1"
fastparquet = "==2024.11.0"
fonttools = "==4.56.0"
fqdn = "==1.5.1"
fsspec = "==2025.2.0"
gitdb = "==4.0.12"
GitPython = "==3.1.44"
greenlet = "==3.1.1"
h11 = "==0.14.0"
h5py = "==3.13.0"
httpcore = "==1.0.7"
httpx = "==0.28.1"
humanfriendly = "==10.0"
idna = "==3.10"
immutables = "==0.21"
iniconfig = "==2.0.0"
ipykernel = "==6.29.5"
ipympl = "==0.9.7"
ipython = "==9.0.1"
ipython_pygments_lexers = "==1.1.1"
ipywidgets = "==8.1.5"
isodate = "==0.7.2"
isoduration = "==20.11.0"
jedi = "==0.19.2"
Jinja2 = "==3.1.6"
jmespath = "==1.0.1"
joblib = "==1.4.2"
json5 = "==0.10.0"
jsonpointer = "==3.0.0"
jsonschema = "==4.23.0"
jsonschema-specifications = "==2024.10.1"
jupyter = "==1.1.1"
jupyter-console = "==6.6.3"
jupyter-events = "==0.12.0"
jupyter-lsp = "==2.2.5"
jupyter_client = "==8.6.3"
jupyter_core = "==5.7.2"
jupyter_server = "==2.15.0"
jupyter_server_terminals = "==0.5.3"
jupyterlab = "==4.3.5"
jupyterlab_pygments = "==0.3.0"
jupyterlab_server = "==2.27.3"
jupyterlab_widgets = "==3.0.13"
kiwisolver = "==1.4.8"
leather = "==0.4.0"
llvmlite = "==0.44.0"
MarkupSafe = "==3.0.2"
matplotlib = "==3.10.1"
matplotlib-inline = "==0.1.7"
mergedeep = "==1.3.4"
methodtools = "==0.4.7"
mistune = "==3.1.2"
mizani = "==0.13.1"
msgpack = "==1.1.0"
msgpack-numpy = "==0.4.8"
narwhals = "==1.29.0"
nbclient = "==0.10.2"
nbconvert = "==7.16.6"
nbformat = "==5.10.4"
ndindex = "==1.9.2"
nest-asyncio = "==1.6.0"
notebook = "==7.3.2"
notebook_shim = "==0.2.4"
numba = "==0.61.0"
numba-progress = "==1.1.3"
numexpr = "==2.10.2"
numpy = "==2.1.3"
nvidia-nccl-cu12 = "==2.25.1"
olefile = "==0.47"
openpyxl = "==3.1.5"
opentims_bruker_bridge = "==1.1.0"
overrides = "==7.7.0"
packaging = "==24.2"
pandas = "==2.2.3"
pandasql = "==0.7.3"
pandocfilters = "==1.5.1"
parsedatetime = "==2.6"
parso = "==0.8.4"
patsy = "==1.0.1"
pexpect = "==4.9.0"
pillow = "==11.1.0"
pip = "==24.0"
plac = "==1.4.3"
platformdirs = "==4.3.6"
plotly = "==6.0.0"
plotnine = "==0.14.5"
pluggy = "==1.5.0"
pony = "==0.7.19"
progressbar = "==2.5"
prometheus_client = "==0.21.1"
prompt_toolkit = "==3.0.50"
psutil = "==7.0.0"
ptyprocess = "==0.7.0"
PuLP = "==2.9.0"
pure_eval = "==0.2.3"
py-cpuinfo = "==9.0.0"
pyarrow = "==19.0.1"
pybind11 = "==2.13.6"
pycparser = "==2.22"
Pygments = "==2.19.1"
PyMySQL = "==1.1.1"
pyparsing = "==3.2.1"
PyQt5 = "==5.15.11"
PyQt5-Qt5 = "==5.15.16"
PyQt5_sip = "==12.17.0"
pytest = "==8.3.5"
python-dateutil = "==2.9.0.post0"
python-json-logger = "==3.2.1"
python-slugify = "==8.0.4"
python_prtree = "==0.6.0"
pytimeparse = "==1.1.8"
pytz = "==2025.1"
PyYAML = "==6.0.2"
pyzmq = "==26.2.1"
referencing = "==0.36.2"
requests = "==2.32.3"
reretry = "==0.11.8"
rfc3339-validator = "==0.1.4"
rfc3986-validator = "==0.1.1"
rpds-py = "==0.23.1"
s3transfer = "==0.11.4"
scikit-learn = "==1.6.1"
scipy = "==1.15.2"
seaborn = "==0.13.2"
Send2Trash = "==1.8.3"
setproctitle = "==1.3.5"
setuptools = "==65.5.0"
six = "==1.17.0"
smart-open = "==7.1.0"
smmap = "==5.0.2"
snakemake = "==8.29.2"
snakemake-interface-common = "==1.17.4"
snakemake-interface-executor-plugins = "==9.3.3"
snakemake-interface-report-plugins = "==1.1.0"
snakemake-interface-storage-plugins = "==3.3.0"
sniffio = "==1.3.1"
soupsieve = "==2.6"
SQLAlchemy = "==2.0.38"
stack-data = "==0.6.3"
statsmodels = "==0.14.4"
tables = "==3.10.2"
tabulate = "==0.9.0"
terminado = "==0.18.1"
text-unidecode = "==1.3"
threadpoolctl = "==3.5.0"
throttler = "==1.2.2"
tinycss2 = "==1.4.0"
toml = "==0.10.2"
tornado = "==6.4.2"
tqdm = "==4.67.1"
traitlets = "==5.14.3"
types-python-dateutil = "==2.9.0.20241206"
typing_extensions = "==4.12.2"
tzdata = "==2025.1"
UpSetPlot = "==0.9.0"
uri-template = "==1.3.0"
urllib3 = "==2.3.0"
uv = "==0.6.4"
wcwidth = "==0.2.13"
webcolors = "==24.11.1"
webencodings = "==0.5.1"
websocket-client = "==1.8.0"
widgetsnbextension = "==4.0.13"
wirerope = "==1.0.0"
wrapt = "==1.17.2"
xgboost = "==2.1.4"
xlrd = "==2.0.1"
yte = "==1.7.0"
zstd = "==1.5.6.6"

[snakemake_targets]
default = "outputs/base/default/G8027/G8045"
bug_report = "outputs/base/debug_MHC1/O13267"

[post_install_script]
bash = "mkdir -p spectra/None.d\ntouch spectra/None.d/analysis.tdf\ntouch spectra/None.d/analysis.tdf_bin\n\necho \"Installing The Old Bruker Fork of Sage.\"\nmkdir -p software/sage/95c2993 \ngit clone git@github.com:midiaIDorg/brukersage.git software/sage/95c2993 --branch 95c2993\nrm -rf software/sage/95c2993/.git\necho \"Done\\n\"\n\nsageVersion=v0.14.7\necho \"Installing $sageVersion\"\nmkdir -p software/sage/$sageVersion \nwget -O - https://github.com/lazear/sage/releases/download/$sageVersion/sage-$sageVersion-x86_64-unknown-linux-gnu.tar.gz | tar -xzvf - -C software/sage/$sageVersion\nmv software/sage/$sageVersion/sage-$sageVersion-x86_64*/* software/sage/$sageVersion\nrm -rf software/sage/$sageVersion/sage-*\n"

[IGNORED_RUN_LOGS]
defcfg_path = "PosixPath('/mnt/bigssd/midia/midia_tester/midia_tester/configs/default.toml')"
full_commandline = "/mnt/bigssd/midia/ve_midiatester/bin/midia_setup --fullconfig ../matteo_devel/devel_no_ms2rescore.toml -o 2025_03_06_devel_no_ms2rescore --use-uv -f --use_venv_instead_virtualenv"
date = "2025-03-06T13:11:52.895829"

[IGNORED_branches]
cached_opentims = "main"
ClusterMS = "main"
dia_common = "main"
kilograms = "main"
mgf_ops = "main"
midia_schemes = "main"
midia_cpp = "main"
midia_pipe = "debug_O13267"
midia_search_engines = "main"
mmapped_df = "main"
MSclusterparser = "main"
opentims = "master"
pandas_ops = "main"
paramidiac = "main"
paramidiac2 = "main"
recapuccino = "main"
savetimspy = "main"
snakemaketools = "devel_longsnake"
midia_fetcher = "main"
midia_pipe_hull = "main"
midia_tester = "main"
tims_tmp = "main"
seops = "main"

[freeze]

[IGNORED_RUN_LOGS.midia_setup_args]
outdir = "PosixPath('2025_03_06_devel_no_ms2rescore')"
fullconfig = "PosixPath('../matteo_devel/devel_no_ms2rescore.toml')"
force = true
pretend = false
skip_self_checks = false
use_uv = true
skip_git_update = false
use_venv_instead_virtualenv = true
number_of_cores_to_use_in_multiprocessing = 50

[IGNORED_RUN_LOGS.git_versions]
cached_opentims = "a5f24cdc7ca3da0cfcccba72c8f6cff8456084b1"
ClusterMS = "cbfccdbb1f6534fb258bb4d99508fb2775ee8c6e"
dia_common = "32fd9642012afc8b3bca7013b439f67d1c82c2c4"
kilograms = "b9f01a4ac697d92150c51d634007707a03f7ca9f"
mgf_ops = "e027503d5c5c50eeff00308c28b28bd1de48c370"
midia_schemes = "e95807a8d23559f008220f74d36364a2ff9118b4"
midia_cpp = "737ebdf879d9c73bd4501d852fffbade4037d509"
midia_pipe = "b41e336a0e24ff0d6612053f3d8eaee7e9479142"
midia_search_engines = "bbf8dfaef3e9f0cf39a8d2596a047d49d6d15830"
mmapped_df = "181998ab2e92b49f9581babca7aa7f59cd40ddb1"
MSclusterparser = "b7cc866a93cef1bb9d0a07087507cd4e7f501e44"
opentims = "2e9274a62aff350a12d24e45a66123100926e83b"
pandas_ops = "48069f143610e25c94e88c112f73f1f995a6259b"
paramidiac = "efe425c31a4816564753e8c39ece519539b09401"
paramidiac2 = "0fce173ae94b12e368ce2a3acc3bdbe0b410a290"
recapuccino = "6b931ff81d0a461e399ca93749f593831bfc90dd"
savetimspy = "1d89fc43175b7092d56cd02679af9e792985fa55"
snakemaketools = "e7f6724bf4ec6293096354061f7984b94461b16d"
midia_fetcher = "099e244d532cc4cc161cb59a55aebe1b33166bf6"
midia_pipe_hull = "9dc63ba21b63cf73f6ef3c78eab89cfc2982251b"
midia_tester = "92cf20e470dfd943bc2726c0da7d7718d3fecdbc"
tims_tmp = "5827533f9c39f23734dceb317a6c4b2183d260c9"
seops = "12b8e6e02abe4e6610d8f871a3b363c8df2b7d9f"
