[python]
pyversion='python3.11'
[git_paths]
opentims='git+ssh://git@github.com/michalsta/opentims'
savetimspy='git+ssh://git@github.com/midiaIDorg/savetimspy'
midia_schemes='git+ssh://git@github.com/midiaIDorg/midia_schemes'
paramidiac='git+ssh://git@github.com/midiaIDorg/paramidiac'
paramidiac2='git+ssh://git@github.com/michalsta/paramidiac2'
dia_common='git+ssh://git@github.com/midiaIDorg/dia_common'
ClusterMS='git+ssh://git@github.com/midiaIDorg/ClusterMS'
kilograms='git+ssh://git@github.com/midiaIDorg/kilograms'
midia_search_engines='git+ssh://git@github.com/midiaIDorg/midia_search_engines'
MSclusterparser='git+ssh://git@github.com/midiaIDorg/MSclusterparser'
pandas_ops='git+ssh://git@github.com/midiaIDorg/pandas_ops'
# py4DFF='http://192.168.1.151:3000/matteo/py4DFF.git'
py4DFF='git+ssh://devel@139.177.177.253:/home/devel/gits/py4DFF'
midia_pipe='git+ssh://git@github.com/midiaIDorg/midia_pipe'
mmapped_df='git+ssh://git@github.com/michalsta/mmapped_df'
cached_opentims='git+ssh://git@github.com/michalsta/cached_opentims.git'
midia_cpp='git+ssh://git@github.com//midiaIDorg/midia_cpp'
[git_versions]
midia_pipe='main'
dia_common='move_schema'
midia_schemes='main'
#dia_common='main'
MSclusterparser='main'
paramidiac='main'
paramidiac2='main'
savetimspy='main'
py4DFF='master'
pandas_ops='main'
kilograms='main'
ClusterMS='main'
opentims='master'
midia_search_engines='main'
mmapped_df='main'
cached_opentims='main'
[requirements_external]
opentims_bruker_bridge=""
snakemake=""
virtualenvwrapper=""
gdown=""
openpyxl=""
ipython=""
matplotlib=""
plotnine=""
seaborn=""
ipykernel=""
[run]
default='snakemake -call diagnostics/recalibration/G8027_cG8605_defaultconf.zip'
hela='snakemake -call diagnostics/recalibration/G8602_cG8605_defaultconf.zip'
short='snakemake -call diagnostics/recalibration/G0004_cG8605_defaultconf.zip'
5p_cnone='snakemake -call diagnostics/recalibration/G8027_cNone_defaultconf.zip diagnostics/recalibration/G8027_cNone_thr_low.zip diagnostics/recalibration/G8027_cNone_thr_high.zip diagnostics/recalibration/G8027_cNone_nothr_high.zip diagnostics/recalibration/G8027_cNone_nothr_low.zip --rerun-incomplete --keep-going'
hela_cnone='snakemake -call diagnostics/recalibration/G8602_cNone_defaultconf.zip diagnostics/recalibration/G8602_cNone_thr_low.zip diagnostics/recalibration/G8602_cNone_thr_high.zip diagnostics/recalibration/G8602_cNone_nothr_high.zip diagnostics/recalibration/G8602_cNone_nothr_low.zip --rerun-incomplete --keep-going'
5p_cself='snakemake -call diagnostics/recalibration/G8027_cSelf_defaultconf.zip diagnostics/recalibration/G8027_cSelf_thr_low.zip diagnostics/recalibration/G8027_cSelf_thr_high.zip diagnostics/recalibration/G8027_cSelf_nothr_high.zip diagnostics/recalibration/G8027_cSelf_nothr_low.zip --rerun-incomplete --keep-going'
hela_cself='snakemake -call diagnostics/recalibration/G8602_cSelf_defaultconf.zip diagnostics/recalibration/G8602_cSelf_thr_low.zip diagnostics/recalibration/G8602_cSelf_thr_high.zip diagnostics/recalibration/G8602_cSelf_nothr_high.zip diagnostics/recalibration/G8602_cSelf_nothr_low.zip --rerun-incomplete --keep-going'
3ms1='snakemake -call diagnostics/quad/G8941/all_done'
hela_sage='snakemake -call outputs/doubleSageWithCheese/G10297/G10303'
self_calib_sage='snakemake -call outputs/doubleSageWithCheese/G10303/G10303'
lukecinka='snakemake -call diagnostics/quad/G8941/all_done diagnostics/quad/G8944/all_done --rerun-incomplete --keep-going'
precursors='snakemake -call diagnostics/quad/G8938/precursors_hist.png'
