[git_versions]
#midia_pipe='stableish'
#dia_common="precursor_prediction"
[snakemake_targets]
default = "out/base/default/dataset=G8605/calibration=none"
unfragmented2 = "out/base/default/dataset=G8605/calibration=none"

