[python]
pyversion = "python3.10"

[git_paths]
opentims = "git+ssh://git@github.com/michalsta/opentims"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
py4DFF = "git+ssh://devel@139.177.177.253:/home/devel/gits/py4DFF"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"

[git_versions]
midia_pipe = "89df682135404e889590ee8400ed5c13dfdab641"
dia_common = "1913e2435f9a97595c68d4d5a37fc0ee29a09af7"
MSclusterparser = "2c20659d1abba59fd6318a19c632a77cc06cae20"
paramidiac = "46d914b5acc3e073a64c0f9126208d5200bfaa5e"
savetimspy = "d0b521e1bc034f4ecf0b2e05eeb7786d8a55aef1"
py4DFF = "ef09601a1ad5cbc48dcceb80327996e7531a7cad"
pandas_ops = "3bc8526a70ff21dd76d04b59b6c84a84ec53083b"
kilograms = "ff5f5483674219974e8f2acfae75b5fc34ff6db9"
ClusterMS = "f9a887d47c7b50583dc2fd7bd88fe80b66186389"
opentims = "48d06301f6ecb6b4e3cba88f990386e96b2e640c"
midia_search_engines = "fea9f7fe9d52935c4b30b1baac6257a57485ff16"
mmapped_df = "59834387df74d8fbc47bd1b50e82e37b60971a68"

[requirements_external]
opentims_bruker_bridge = ""
snakemake = "==7.25.3"
virtualenvwrapper = "==4.8.4"
gdown = "==4.7.1"
openpyxl = "==3.1.2"
ipython = "==8.13.2"
matplotlib = "==3.7.1"
plotnine = "==0.10.1"
seaborn = "==0.12.2"
anyio = "==3.7.0"
appdirs = "==1.4.4"
argon2-cffi = "==21.3.0"
argon2-cffi-bindings = "==21.2.0"
arrow = "==1.2.3"
asttokens = "==2.2.1"
async-lru = "==2.0.2"
attrs = "==23.1.0"
Babel = "==2.12.1"
backcall = "==0.2.0"
beautifulsoup4 = "==4.12.2"
bleach = "==6.0.0"
blosc2 = "==2.0.0"
certifi = "==2022.12.7"
cffi = "==1.15.1"
cfgv = "==3.3.1"
charset-normalizer = "==3.1.0"
comm = "==0.1.3"
ConfigArgParse = "==1.5.3"
connection-pool = "==0.0.3"
contourpy = "==1.0.7"
cramjam = "==2.6.2"
cycler = "==0.11.0"
Cython = "==0.29.34"
datrie = "==0.8.2"
debugpy = "==1.6.7"
decorator = "==5.1.1"
defusedxml = "==0.7.1"
distlib = "==0.3.6"
docutils = "==0.19"
dpath = "==2.1.5"
duckdb = "==0.7.1"
et-xmlfile = "==1.1.0"
exceptiongroup = "==1.1.1"
executing = "==1.2.0"
fastjsonschema = "==2.16.3"
fastparquet = "==2023.4.0"
filelock = "==3.12.0"
fonttools = "==4.39.3"
fqdn = "==1.5.1"
fsspec = "==2023.4.0"
furious-fastas = "==0.1.5"
gitdb = "==4.0.10"
GitPython = "==3.1.31"
greenlet = "==2.0.2"
h5py = "==3.8.0"
hdbscan = "==0.8.29"
humanfriendly = "==10.0"
identify = "==2.5.24"
idna = "==3.4"
iniconfig = "==2.0.0"
intervaltree = "==3.1.0"
ipykernel = "==6.23.1"
isoduration = "==20.11.0"
IsoSpecPy = "==2.2.1"
jedi = "==0.18.2"
Jinja2 = "==3.1.2"
joblib = "==1.2.0"
json5 = "==0.9.14"
jsonpointer = "==2.3"
jsonschema = "==4.17.3"
jupyter-events = "==0.6.3"
jupyter-lsp = "==2.2.0"
jupyter_client = "==8.2.0"
jupyter_core = "==5.3.0"
jupyter_server = "==2.6.0"
jupyter_server_terminals = "==0.4.4"
jupyterlab = "==4.0.0"
jupyterlab-pygments = "==0.2.2"
jupyterlab_server = "==2.22.1"
kiwisolver = "==1.4.4"
llvmlite = "==0.40.0"
MarkupSafe = "==2.1.2"
matplotlib-inline = "==0.1.6"
methodtools = "==0.4.7"
mistune = "==2.0.5"
mizani = "==0.9.0"
msgpack = "==1.0.5"
msgpack-numpy = "==0.4.8"
nbclient = "==0.8.0"
nbconvert = "==7.4.0"
nbformat = "==5.8.0"
nest-asyncio = "==1.5.6"
networkx = "==3.1"
nodeenv = "==1.8.0"
notebook_shim = "==0.2.3"
numba = "==0.57.0"
numexpr = "==2.8.4"
numpy = "==1.24.3"
opentims-bruker-bridge = "==1.1.0"
overrides = "==7.3.1"
packaging = "==23.1"
pandas = "==2.0.1"
pandasql = "==0.7.3"
pandocfilters = "==1.5.0"
parso = "==0.8.3"
patsy = "==0.5.3"
pbr = "==5.11.1"
pexpect = "==4.8.0"
pickleshare = "==0.7.5"
Pillow = "==9.5.0"
pip = "==23.1.2"
plac = "==1.3.5"
platformdirs = "==3.5.0"
pluggy = "==1.0.0"
pre-commit = "==3.3.2"
prometheus-client = "==0.17.0"
prompt-toolkit = "==3.0.38"
psutil = "==5.9.5"
ptyprocess = "==0.7.0"
pulearn = "==0.0.7"
PuLP = "==2.7.0"
pure-eval = "==0.2.2"
py-cpuinfo = "==9.0.0"
py-expression-eval = "==0.3.14"
pyarrow = "==12.0.0"
pybind11 = "==2.10.4"
pycparser = "==2.21"
Pygments = "==2.15.1"
pyparsing = "==3.0.9"
pyrsistent = "==0.19.3"
PySocks = "==1.7.1"
pytest = "==7.3.1"
python-dateutil = "==2.8.2"
python-json-logger = "==2.0.7"
python-prtree = "==0.6.0"
pytz = "==2023.3"
PyYAML = "==6.0"
pyzmq = "==25.1.0"
requests = "==2.30.0"
reretry = "==0.11.8"
rfc3339-validator = "==0.1.4"
rfc3986-validator = "==0.1.1"
scikit-learn = "==1.2.2"
scipy = "==1.10.1"
Send2Trash = "==1.8.2"
setproctitle = "==1.3.2"
setuptools = "==59.6.0"
six = "==1.16.0"
sklearn = "==0.0.post4"
smart-open = "==6.3.0"
smmap = "==5.0.0"
sniffio = "==1.3.0"
sortedcontainers = "==2.4.0"
soupsieve = "==2.4.1"
SQLAlchemy = "==2.0.12"
stack-data = "==0.6.2"
statsmodels = "==0.14.0"
stevedore = "==5.0.0"
stopit = "==1.1.2"
tables = "==3.8.0"
tabulate = "==0.9.0"
terminado = "==0.17.1"
threadpoolctl = "==3.1.0"
throttler = "==1.2.2"
tinycss2 = "==1.2.1"
toml = "==0.10.2"
tomli = "==2.0.1"
toposort = "==1.10"
tornado = "==6.3.2"
tqdm = "==4.65.0"
traitlets = "==5.9.0"
typing_extensions = "==4.5.0"
tzdata = "==2023.3"
uri-template = "==1.2.0"
urllib3 = "==2.0.2"
virtualenv = "==20.23.0"
virtualenv-clone = "==0.5.7"
wcwidth = "==0.2.6"
webcolors = "==1.13"
webencodings = "==0.5.1"
websocket-client = "==1.5.2"
wheel = "==0.37.1"
wirerope = "==0.4.7"
wrapt = "==1.15.0"
xgboost = "==1.7.5"
yte = "==1.5.1"
zstd = "==1.5.5.1"

[run]
default = "snakemake -call diagnostics/recalibration/G8027_cG8605_defaultconf.zip"
hela = "snakemake -call diagnostics/recalibration/G8602_cG8605_defaultconf.zip"
short = "snakemake -call diagnostics/recalibration/G0004_cG8605_defaultconf.zip"

[IGNORED_branches]
opentims = "master"
savetimspy = "main"
paramidiac = "main"
dia_common = "main"
ClusterMS = "main"
kilograms = "main"
midia_search_engines = "main"
MSclusterparser = "main"
pandas_ops = "main"
py4DFF = "master"
midia_pipe = "main"
mmapped_df = "main"

[freeze]
