[git_versions]
midia_pipe = "midiaID_november_rain_paper"
ClusterMS = "midiaID_november_rain_paper"
MSclusterparser = "midiaID_november_rain_paper"
cached_opentims = "midiaID_november_rain_paper"
dia_common = "midiaID_november_rain_paper"
kilograms = "main"
mgf_ops = "main"
midia_cpp = "main"
midia_fetcher = "main"
midia_pipe_hull = "main"
midia_schemes = "main"
midia_search_engines = "midiaID_november_rain_paper"
mmapped_df = "midiaID_november_rain_paper"
opentims = "midiaID_november_rain_paper"
pandas_ops = "main"
paramidiac = "midiaID_november_rain_paper"
paramidiac2 = "main"
recapuccino = "main"
savetimspy = "main"
snakemaketools = "main"

