[git_versions]
midia_pipe="devel_altsage"
cached_opentims = "main"
ClusterMS = "main"
dia_common = "main"
kilograms = "main"
mgf_ops = "main"
midia_schemes = "main"
midia_cpp = "main"
midia_search_engines = "main"
mmapped_df = "main"
MSclusterparser = "main"
opentims = "master"
pandas_ops = "main"
paramidiac = "main"
paramidiac2 = "main"
recapuccino = "main"
savetimspy = "main"
snakemaketools = "main"
midia_fetcher = "main"
midia_pipe_hull = "main"

