[python]
pyversion='python3.11'

[git_paths]
mmapped_df='git+ssh://git@github.com/michalsta/mmapped_df'
opentims='git+ssh://git@github.com/michalsta/opentims'
savetimspy='git+ssh://git@github.com/midiaIDorg/savetimspy'
paramidiac='git+ssh://git@github.com/midiaIDorg/paramidiac'
dia_common='git+ssh://git@github.com/midiaIDorg/dia_common'
ClusterMS='git+ssh://git@github.com/midiaIDorg/ClusterMS'
kilograms='git+ssh://git@github.com/midiaIDorg/kilograms'
midia_search_engines='git+ssh://git@github.com/midiaIDorg/midia_search_engines'
MSclusterparser='git+ssh://git@github.com/midiaIDorg/MSclusterparser'
pandas_ops='git+ssh://git@github.com/midiaIDorg/pandas_ops'
py4DFF='git+ssh://devel@139.177.177.253:/home/devel/gits/py4DFF'
midia_pipe='git+ssh://git@github.com/midiaIDorg/midia_pipe'
cached_opentims='git+ssh://git@github.com/michalsta/cached_opentims.git'
midia_cpp='git+ssh://git@github.com/michalsta/midia_cpp'

[git_versions]
mmapped_df='main'
midia_pipe='main'
dia_common='41a0fe418164e8203851bea1ad8980d4eb171841'
MSclusterparser='main'
paramidiac='main'
savetimspy='main'
py4DFF='master'
pandas_ops='main'
kilograms='main'
ClusterMS='main'
opentims='master'
midia_search_engines='main'
cached_opentims='main'
midia_cpp='main'

[requirements_external]
agate = "1.7"
agate-dbf = "0.2.2"
agate-excel = "0.2.5"
agate-sql = "0.5.9"
appdirs = "1.4.4"
asttokens = "2.2.1"
attrs = "23.1.0"
Babel = "2.12.1"
backcall = "0.2.0"
beautifulsoup4 = "4.12.2"
blosc2 = "2.0.0"
certifi = "2023.7.22"
cffi = "1.15.1"
charset-normalizer = "3.2.0"
comm = "0.1.4"
ConfigArgParse = "1.7"
connection-pool = "0.0.3"
contourpy = "1.1.0"
cramjam = "2.7.0"
csvkit = "1.1.1"
cycler = "0.11.0"
Cython = "0.29.36"
datrie = "0.8.2"
dbfread = "2.0.7"
debugpy = "1.6.7.post1"
decorator = "5.1.1"
distlib = "0.3.7"
docutils = "0.20.1"
dpath = "2.1.6"
duckdb = "0.8.1"
et-xmlfile = "1.1.0"
executing = "1.2.0"
fastjsonschema = "2.18.0"
fastparquet = "2023.7.0"
filelock = "3.12.2"
fonttools = "4.42.0"
fsspec = "2023.6.0"
gdown = "4.7.1"
gitdb = "4.0.10"
GitPython = "3.1.32"
greenlet = "2.0.2"
h5py = "3.9.0"
hdbscan = "0.8.33"
humanfriendly = "10.0"
idna = "3.4"
intervaltree = "3.1.0"
ipykernel = "6.25.1"
ipython = "8.14.0"
isodate = "0.6.1"
jedi = "0.19.0"
Jinja2 = "3.1.2"
joblib = "1.3.2"
jsonschema = "4.19.0"
jsonschema-specifications = "2023.7.1"
jupyter_client = "8.3.0"
jupyter_core = "5.3.1"
kiwisolver = "1.4.4"
leather = "0.3.4"
llvmlite = "0.40.1"
MarkupSafe = "2.1.3"
matplotlib = "3.7.2"
matplotlib-inline = "0.1.6"
methodtools = "0.4.7"
mizani = "0.9.2"
msgpack = "1.0.5"
msgpack-numpy = "0.4.8"
nbformat = "5.9.2"
nest-asyncio = "1.5.7"
networkx = "3.1"
numba = "0.57.1"
numexpr = "2.8.5"
numpy = "1.24.4"
olefile = "0.46"
openpyxl = "3.1.2"
opentims-bruker-bridge = "1.1.0"
packaging = "23.1"
pandas = "2.0.3"
pandasql = "0.7.3"
parsedatetime = "2.6"
parso = "0.8.3"
patsy = "0.5.3"
pbr = "5.11.1"
pexpect = "4.8.0"
pickleshare = "0.7.5"
Pillow = "10.0.0"
plac = "1.3.5"
platformdirs = "3.10.0"
plotnine = "0.12.2"
polars = "0.18.15"
prompt-toolkit = "3.0.39"
psutil = "5.9.5"
ptyprocess = "0.7.0"
PuLP = "2.7.0"
pure-eval = "0.2.2"
py-cpuinfo = "9.0.0"
py-expression-eval = "0.3.14"
pyarrow = "12.0.1"
pybind11 = "2.11.1"
pycparser = "2.21"
Pygments = "2.16.1"
pyparsing = "3.0.9"
PySocks = "1.7.1"
python-dateutil = "2.8.2"
python-prtree = "0.6.0"
python-slugify = "8.0.1"
pytimeparse = "1.1.8"
pytz = "2023.3"
PyYAML = "6.0.1"
pyzmq = "25.1.1"
referencing = "0.30.2"
requests = "2.31.0"
reretry = "0.11.8"
rpds-py = "0.9.2"
scikit-learn = "1.3.0"
scipy = "1.11.2"
seaborn = "0.12.2"
setproctitle = "1.3.2"
six = "1.16.0"
smart-open = "6.3.0"
smmap = "5.0.0"
snakemake = "7.32.3"
sortedcontainers = "2.4.0"
soupsieve = "2.4.1"
SQLAlchemy = "1.4.49"
stack-data = "0.6.2"
statsmodels = "0.14.0"
stevedore = "5.1.0"
stopit = "1.1.2"
tables = "3.8.0"
tabulate = "0.9.0"
text-unidecode = "1.3"
threadpoolctl = "3.2.0"
throttler = "1.2.2"
toml = "0.10.2"
toposort = "1.10"
tornado = "6.3.3"
tqdm = "4.66.1"
traitlets = "5.9.0"
tzdata = "2023.3"
urllib3 = "2.0.4"
virtualenv = "20.24.3"
virtualenv-clone = "0.5.7"
virtualenvwrapper = "4.8.4"
wcwidth = "0.2.6"
wirerope = "0.4.7"
wrapt = "1.15.0"
xgboost = "1.7.6"
xlrd = "2.0.1"
yte = "1.5.1"
zstd = "1.5.5.1"

[run]
default='snakemake -call diagnostics/recalibration/G8027_cG8605_defaultconf.zip'
hela='snakemake -call diagnostics/recalibration/G8602_cG8605_defaultconf.zip'
short='snakemake -call diagnostics/recalibration/G0004_cG8605_defaultconf.zip'
thpr5p='snakemake -call fragpipe/raw/rough_fragpipe_fullest_xgboost_tpr0.98/G8027_cNone_THPRScombined_d4_i4DFF_i4DFF'
test_5P_5DFF_SAGE_mz_recalibration = 'snakemake -call outputs/doubleSageWithCheese/G8027/G8045'
test_HeLa_5DFF_SAGE_mz_recalibration = 'snakemake -call outputs/doubleSageWithCheese/G8602/G8605'
test_3ms1='snakemake -n cluster_stats/G8027/G8045/b5e24bd5ca2/5D/0/ms2.parquet'

