[python]
pyversion = "python3.10"

[git_paths]
opentims = "git+ssh://git@github.com/michalsta/opentims"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
py4DFF = "git+ssh://devel@139.177.177.253:/home/devel/gits/py4DFF"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"

[git_versions]
midia_pipe = "main"
dia_common = "41a0fe418164e8203851bea1ad8980d4eb171841"
MSclusterparser = "main"
paramidiac = "main"
savetimspy = "main"
py4DFF = "main"
pandas_ops = "main"
kilograms = "main"
ClusterMS = "main"
opentims = "master"
midia_search_engines = "main"
mmapped_df = "main"

[requirements_external]
opentims_bruker_bridge=""
snakemake=""
virtualenvwrapper=""
gdown=""
openpyxl=""
ipython=""
matplotlib=""
plotnine=""
seaborn=""
[run]
default = "snakemake -call diagnostics/recalibration/G8027_cG8605_defaultconf.zip"
hela = "snakemake -call outputs/ml_debugging/G8602/G8605/{narrow,wide}RoughMatches/{stringent1stGen_p12f15,p12f15nd}/p8f8/novelty_detection_ellipse/{rankMax5,rankMax10,rankMax15,rankMax20,MahalanobisQuantile60,MahalanobisQuantile70,MahalanobisQuantile80,MahalanobisQuantile90,MahalanobisQuantile95}"
5P = "snakemake -call outputs/ml_debugging/G8027/G8045/{narrow,wide}RoughMatches/{stringent1stGen_p12f15,p12f15nd}/p8f8/novelty_detection_ellipse/{rankMax5,rankMax10,rankMax15,rankMax20,MahalanobisQuantile60,MahalanobisQuantile70,MahalanobisQuantile80,MahalanobisQuantile90,MahalanobisQuantile95}"


[IGNORED_branches]
opentims = "master"
savetimspy = "main"
paramidiac = "main"
dia_common = "main"
ClusterMS = "main"
kilograms = "main"
midia_search_engines = "main"
MSclusterparser = "main"
pandas_ops = "main"
py4DFF = "master"
midia_pipe = "feature/ML"
mmapped_df = "main"

[freeze]
