[python]
pyversion = "python3.11"

[git_paths]
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"
opentims = "git+ssh://git@github.com/michalsta/opentims"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
cached_opentims = "git+ssh://git@github.com/michalsta/cached_opentims.git"
midia_cpp = "git+ssh://git@github.com/midiaIDorg/midia_cpp"

[git_versions]
mmapped_df = "582bd80c863c0549f37a42e7313f481eae4d414b"
midia_pipe = "81fefbe272a60e8583d386c22d181793e6e04451"
dia_common = "932ed1782c6dc3d7bb40d457f112bef38d8c7cc8"
MSclusterparser = "83b82a848e54d918a929bf5b0d55425fb0d75a05"
paramidiac = "98a4f235d9b4b48c7bd70741882e0ffdf0b7a466"
savetimspy = "d0b521e1bc034f4ecf0b2e05eeb7786d8a55aef1"
py4DFF = "master"
pandas_ops = "80a7328e372457fc45b687d84afd5f6b0af48b36"
kilograms = "f7bb5ea228e482bdc0486ed601c30b972bf41e47"
ClusterMS = "f9a887d47c7b50583dc2fd7bd88fe80b66186389"
opentims = "b74a359b0caed74b4480bd0ef5a6a8fbe4911fdb"
midia_search_engines = "e9d5c02fe129d26e7e6cd3252ae138cbf16b3d57"
cached_opentims = "aedcf00621183683a51908bb289941a8ed748fe5"
midia_cpp = "f08160ce19acb9f4c0300a0a13b3d46074446aa3"

[requirements_external]
opentims_bruker_bridge = ""
snakemake = "==7.32.3"
virtualenvwrapper = "==4.8.4"
gdown = "==4.7.1"
openpyxl = "==3.1.2"
ipython = "==8.15.0"
matplotlib = "==3.7.2"
plotnine = "==0.12.3"
seaborn = "==0.12.2"
csvkit = "==1.1.1"
ipykernel = "==6.25.2"
jupyter = "==1.0.0"
jupyterlab = "==4.0.5"
pandas = "==2.0.3"
agate = "==1.7.1"
agate-dbf = "==0.2.2"
agate-excel = "==0.2.5"
agate-sql = "==0.5.9"
anyio = "==4.0.0"
appdirs = "==1.4.4"
argon2-cffi = "==23.1.0"
argon2-cffi-bindings = "==21.2.0"
arrow = "==1.2.3"
asttokens = "==2.4.0"
async-lru = "==2.0.4"
attrs = "==23.1.0"
Babel = "==2.12.1"
backcall = "==0.2.0"
beautifulsoup4 = "==4.12.2"
bleach = "==6.0.0"
blosc2 = "==2.0.0"
certifi = "==2023.7.22"
cffi = "==1.15.1"
charset-normalizer = "==3.2.0"
comm = "==0.1.4"
ConfigArgParse = "==1.7"
connection-pool = "==0.0.3"
contourpy = "==1.1.0"
cramjam = "==2.7.0"
cycler = "==0.11.0"
Cython = "==0.29.36"
datrie = "==0.8.2"
dbfread = "==2.0.7"
debugpy = "==1.7.0"
decorator = "==5.1.1"
defusedxml = "==0.7.1"
distlib = "==0.3.7"
docutils = "==0.20.1"
dpath = "==2.1.6"
duckdb = "==0.8.1"
et-xmlfile = "==1.1.0"
executing = "==1.2.0"
fastjsonschema = "==2.18.0"
fastparquet = "==2023.8.0"
filelock = "==3.12.3"
fonttools = "==4.42.1"
fqdn = "==1.5.1"
fsspec = "==2023.9.0"
gitdb = "==4.0.10"
GitPython = "==3.1.35"
greenlet = "==2.0.2"
h5py = "==3.9.0"
hdbscan = "==0.8.33"
humanfriendly = "==10.0"
idna = "==3.4"
intervaltree = "==3.1.0"
ipython-genutils = "==0.2.0"
ipywidgets = "==8.1.0"
isodate = "==0.6.1"
isoduration = "==20.11.0"
jedi = "==0.19.0"
Jinja2 = "==3.1.2"
joblib = "==1.3.2"
json5 = "==0.9.14"
jsonpointer = "==2.4"
jsonschema = "==4.19.0"
jsonschema-specifications = "==2023.7.1"
jupyter-console = "==6.6.3"
jupyter-events = "==0.7.0"
jupyter-lsp = "==2.2.0"
jupyter_client = "==8.3.1"
jupyter_core = "==5.3.1"
jupyter_server = "==2.7.3"
jupyter_server_terminals = "==0.4.4"
jupyterlab-pygments = "==0.2.2"
jupyterlab-widgets = "==3.0.8"
jupyterlab_server = "==2.24.0"
kiwisolver = "==1.4.5"
leather = "==0.3.4"
llvmlite = "==0.40.1"
MarkupSafe = "==2.1.3"
matplotlib-inline = "==0.1.6"
methodtools = "==0.4.7"
mistune = "==3.0.1"
mizani = "==0.9.3"
msgpack = "==1.0.5"
msgpack-numpy = "==0.4.8"
nbclient = "==0.8.0"
nbconvert = "==7.8.0"
nbformat = "==5.9.2"
nest-asyncio = "==1.5.7"
networkx = "==3.1"
notebook = "==7.0.3"
notebook_shim = "==0.2.3"
numba = "==0.57.1"
numexpr = "==2.8.5"
numpy = "==1.24.4"
olefile = "==0.46"
opentims-bruker-bridge = "==1.1.0"
overrides = "==7.4.0"
packaging = "==23.1"
pandasql = "==0.7.3"
pandocfilters = "==1.5.0"
parsedatetime = "==2.6"
parso = "==0.8.3"
patsy = "==0.5.3"
pbr = "==5.11.1"
pexpect = "==4.8.0"
pickleshare = "==0.7.5"
Pillow = "==10.0.0"
pip = "==23.2.1"
plac = "==1.3.5"
platformdirs = "==3.10.0"
polars = "==0.19.2"
prometheus-client = "==0.17.1"
prompt-toolkit = "==3.0.39"
psutil = "==5.9.5"
ptyprocess = "==0.7.0"
PuLP = "==2.7.0"
pure-eval = "==0.2.2"
py-cpuinfo = "==9.0.0"
py-expression-eval = "==0.3.14"
pyarrow = "==13.0.0"
pybind11 = "==2.11.1"
pycparser = "==2.21"
Pygments = "==2.16.1"
pyparsing = "==3.0.9"
PySocks = "==1.7.1"
python-dateutil = "==2.8.2"
python-json-logger = "==2.0.7"
python-prtree = "==0.6.0"
python-slugify = "==8.0.1"
pytimeparse = "==1.1.8"
pytz = "==2023.3.post1"
PyYAML = "==6.0.1"
pyzmq = "==25.1.1"
qtconsole = "==5.4.4"
QtPy = "==2.4.0"
referencing = "==0.30.2"
requests = "==2.31.0"
reretry = "==0.11.8"
rfc3339-validator = "==0.1.4"
rfc3986-validator = "==0.1.1"
rpds-py = "==0.10.2"
scikit-learn = "==1.3.0"
scipy = "==1.11.2"
Send2Trash = "==1.8.2"
setproctitle = "==1.3.2"
setuptools = "==59.6.0"
six = "==1.16.0"
smart-open = "==6.4.0"
smmap = "==5.0.0"
sniffio = "==1.3.0"
sortedcontainers = "==2.4.0"
soupsieve = "==2.5"
SQLAlchemy = "==1.4.49"
stack-data = "==0.6.2"
statsmodels = "==0.14.0"
stevedore = "==5.1.0"
stopit = "==1.1.2"
tables = "==3.8.0"
tabulate = "==0.9.0"
terminado = "==0.17.1"
text-unidecode = "==1.3"
threadpoolctl = "==3.2.0"
throttler = "==1.2.2"
tinycss2 = "==1.2.1"
toml = "==0.10.2"
toposort = "==1.10"
tornado = "==6.3.3"
tqdm = "==4.66.1"
traitlets = "==5.9.0"
tzdata = "==2023.3"
uri-template = "==1.3.0"
urllib3 = "==2.0.4"
virtualenv = "==20.24.5"
virtualenv-clone = "==0.5.7"
wcwidth = "==0.2.6"
webcolors = "==1.13"
webencodings = "==0.5.1"
websocket-client = "==1.6.3"
wheel = "==0.37.1"
widgetsnbextension = "==4.0.8"
wirerope = "==0.4.7"
wrapt = "==1.15.0"
xgboost = "==1.7.6"
xlrd = "==2.0.1"
yte = "==1.5.1"
zstd = "==1.5.5.1"

[run]
default = "snakemake -call diagnostics/recalibration/G8027_cG8605_defaultconf.zip"
hela = "snakemake -call diagnostics/recalibration/G8602_cG8605_defaultconf.zip"
short = "snakemake -call diagnostics/recalibration/G0004_cG8605_defaultconf.zip"
thpr5p = "snakemake -call fragpipe/raw/rough_fragpipe_fullest_xgboost_tpr0.98/G8027_cNone_THPRScombined_d4_i4DFF_i4DFF"
test_5P_5DFF_SAGE_mz_recalibration = "snakemake -call outputs/doubleSageWithCheese/G8027/G8045"
test_HeLa_5DFF_SAGE_mz_recalibration = "snakemake -call outputs/doubleSageWithCheese/G8602/G8605"
test_3ms1 = "snakemake -n cluster_stats/G8027/G8045/b5e24bd5ca2/5D/0/ms2.parquet"
self_calib_sage = "snakemake -call outputs/doubleSageWithCheese/G10303/G10303"

[IGNORED_RUN_LOGS]
defcfg_path = "PosixPath('/home/matteo/MIDIA/midia_tester/midia_tester/configs/default.toml')"

[IGNORED_branches]
mmapped_df = "main"
opentims = "master"
savetimspy = "main"
paramidiac = "main"
dia_common = "main"
ClusterMS = "main"
kilograms = "main"
midia_search_engines = "main"
MSclusterparser = "main"
pandas_ops = "main"
midia_pipe = "main"
cached_opentims = "main"
midia_cpp = "main"

[freeze]

[IGNORED_RUN_LOGS.midia_setup_args]
outdir = "PosixPath('2023_09_11_ducky')"
force = false
