[python]
pyversion = "python3.11"

[git_paths]
opentims = "git+ssh://git@github.com/michalsta/opentims"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
py4DFF = "git+ssh://devel@139.177.177.253:/home/devel/gits/py4DFF"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"

[git_versions]
midia_pipe = "04ab92ca764581d8961298fea6a83ccfcecba08f"
dia_common = "4eed76962e6637cc04a5014c6c30d9a0f613559c"
MSclusterparser = "2c20659d1abba59fd6318a19c632a77cc06cae20"
paramidiac = "a2d15a53b0c48a01f0125b7b9ae17b01078fbdcb"
savetimspy = "d0b521e1bc034f4ecf0b2e05eeb7786d8a55aef1"
py4DFF = "c6096f9e3853b40481d576f7f9885e96a48e28ec"
pandas_ops = "8df57e24c8e950a87dcb51ae425ae8d8b4a999a2"
kilograms = "ff5f5483674219974e8f2acfae75b5fc34ff6db9"
ClusterMS = "f9a887d47c7b50583dc2fd7bd88fe80b66186389"
opentims = "28b38356a233f65e47e7ce290d4be20552f48014"
midia_search_engines = "fea9f7fe9d52935c4b30b1baac6257a57485ff16"
mmapped_df = "59834387df74d8fbc47bd1b50e82e37b60971a68"

[requirements_external]
opentims_bruker_bridge = ""
snakemake = "==7.30.1"
virtualenvwrapper = "==4.8.4"
gdown = "==4.7.1"
openpyxl = "==3.1.2"
ipython = "==8.14.0"
matplotlib = "==3.7.2"
plotnine = "==0.12.1"
seaborn = "==0.12.2"
csvkit = "==1.1.1"
agate = "==1.7.1"
agate-dbf = "==0.2.2"
agate-excel = "==0.2.5"
agate-sql = "==0.5.9"
appdirs = "==1.4.4"
asttokens = "==2.2.1"
attrs = "==23.1.0"
Babel = "==2.12.1"
backcall = "==0.2.0"
beautifulsoup4 = "==4.12.2"
blosc2 = "==2.0.0"
certifi = "==2023.5.7"
cffi = "==1.15.1"
charset-normalizer = "==3.2.0"
ConfigArgParse = "==1.5.5"
connection-pool = "==0.0.3"
contourpy = "==1.1.0"
cramjam = "==2.6.2"
cycler = "==0.11.0"
Cython = "==0.29.36"
datrie = "==0.8.2"
dbfread = "==2.0.7"
decorator = "==5.1.1"
distlib = "==0.3.6"
docutils = "==0.20.1"
dpath = "==2.1.6"
duckdb = "==0.8.1"
et-xmlfile = "==1.1.0"
executing = "==1.2.0"
fastjsonschema = "==2.17.1"
fastparquet = "==2023.7.0"
filelock = "==3.12.2"
fonttools = "==4.40.0"
fsspec = "==2023.6.0"
gitdb = "==4.0.10"
GitPython = "==3.1.32"
greenlet = "==2.0.2"
h5py = "==3.9.0"
hdbscan = "==0.8.30"
humanfriendly = "==10.0"
idna = "==3.4"
intervaltree = "==3.1.0"
isodate = "==0.6.1"
jedi = "==0.18.2"
Jinja2 = "==3.1.2"
joblib = "==1.3.1"
jsonschema = "==4.18.1"
jsonschema-specifications = "==2023.6.1"
jupyter_core = "==5.3.1"
kiwisolver = "==1.4.4"
leather = "==0.3.4"
llvmlite = "==0.40.1"
MarkupSafe = "==2.1.3"
matplotlib-inline = "==0.1.6"
methodtools = "==0.4.7"
mizani = "==0.9.2"
msgpack = "==1.0.5"
msgpack-numpy = "==0.4.8"
nbformat = "==5.9.1"
networkx = "==3.1"
numba = "==0.57.1"
numexpr = "==2.8.4"
numpy = "==1.24.4"
olefile = "==0.46"
opentims-bruker-bridge = "==1.1.0"
packaging = "==23.1"
pandas = "==2.0.3"
pandasql = "==0.7.3"
parsedatetime = "==2.6"
parso = "==0.8.3"
patsy = "==0.5.3"
pbr = "==5.11.1"
pexpect = "==4.8.0"
pickleshare = "==0.7.5"
Pillow = "==10.0.0"
pip = "==23.1.2"
plac = "==1.3.5"
platformdirs = "==3.8.1"
prompt-toolkit = "==3.0.39"
psutil = "==5.9.5"
ptyprocess = "==0.7.0"
PuLP = "==2.7.0"
pure-eval = "==0.2.2"
py-cpuinfo = "==9.0.0"
py-expression-eval = "==0.3.14"
pyarrow = "==12.0.1"
pybind11 = "==2.10.4"
pycparser = "==2.21"
Pygments = "==2.15.1"
pyparsing = "==3.0.9"
PySocks = "==1.7.1"
python-dateutil = "==2.8.2"
python-prtree = "==0.6.0"
python-slugify = "==8.0.1"
pytimeparse = "==1.1.8"
pytz = "==2023.3"
PyYAML = "==6.0"
referencing = "==0.29.1"
requests = "==2.31.0"
reretry = "==0.11.8"
rpds-py = "==0.8.10"
scikit-learn = "==1.3.0"
scipy = "==1.11.1"
setproctitle = "==1.3.2"
setuptools = "==67.8.0"
six = "==1.16.0"
smart-open = "==6.3.0"
smmap = "==5.0.0"
sortedcontainers = "==2.4.0"
soupsieve = "==2.4.1"
SQLAlchemy = "==1.4.49"
stack-data = "==0.6.2"
statsmodels = "==0.14.0"
stevedore = "==5.1.0"
stopit = "==1.1.2"
tables = "==3.8.0"
tabulate = "==0.9.0"
text-unidecode = "==1.3"
threadpoolctl = "==3.1.0"
throttler = "==1.2.2"
toml = "==0.10.2"
toposort = "==1.10"
tqdm = "==4.65.0"
traitlets = "==5.9.0"
tzdata = "==2023.3"
urllib3 = "==2.0.3"
virtualenv = "==20.23.1"
virtualenv-clone = "==0.5.7"
wcwidth = "==0.2.6"
wheel = "==0.40.0"
wirerope = "==0.4.7"
wrapt = "==1.15.0"
xgboost = "==1.7.6"
xlrd = "==2.0.1"
yte = "==1.5.1"
zstd = "==1.5.5.1"

[run]
default = "snakemake -call outputs/doubleSageWithCheese/G8027/G8045"
test_5P = "snakemake -call outputs/doubleSageWithCheese/G8027/G8045"
test_hela = "snakemake -call outputs/doubleSageWithCheese/G6802/G6805"

[IGNORED_branches]
opentims = "master"
savetimspy = "main"
paramidiac = "main"
dia_common = "main"
ClusterMS = "main"
kilograms = "main"
midia_search_engines = "main"
MSclusterparser = "main"
pandas_ops = "main"
py4DFF = "master"
midia_pipe = "main"
mmapped_df = "main"

[freeze]
