[python]
pyversion = "python3.11"

[git_paths]
cached_opentims = "git+ssh://git@github.com/michalsta/cached_opentims.git"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
midia_cpp = "git+ssh://git@github.com/midiaIDorg/midia_cpp"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
opentims = "git+ssh://git@github.com/michalsta/opentims"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
recapuccino = "git@github.com:midiaIDorg/recapuccino.git"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"

[git_versions]
cached_opentims = "0b49304a4e4d317abebfb8599938fc2ea81c3992"
ClusterMS = "f9a887d47c7b50583dc2fd7bd88fe80b66186389"
dia_common = "e5a4813321ffd351f9d603791251ce6f941a0653"
kilograms = "ba8362e3844d3b9df7012702117e9e375a97a0d6"
midia_cpp = "d7a003b7beb33170c3348d776f53f190fafc5921"
midia_pipe = "4ffbfed4e7d705cce06833ae324b0d078688f8dd"
midia_search_engines = "e1f3f6a0850707ea0c8ddd3bceddc1ff8e5bb94f"
mmapped_df = "ab68eb121751d05b4600d452cdd9dfb04761c728"
MSclusterparser = "e1ce4e2f3b416731fdfaa14a9a53f37735c6e9af"
opentims = "b74a359b0caed74b4480bd0ef5a6a8fbe4911fdb"
pandas_ops = "6a5c6de0ef0ef06d792ced994583cc42165782de"
paramidiac = "9ba9807ad21d985d8d29bbd67abc1af5aa24f2fc"
py4DFF = "master"
recapuccino = "ca268a00b7f35ec883abb510d820402aecf4354c"
savetimspy = "394fdd7984d5e9c578183043d595edfc29e0217d"

[requirements_external]
csvkit = "==1.3.0"
gdown = "==4.7.1"
ipykernel = "==6.26.0"
ipython = "==8.17.2"
jupyter = "==1.0.0"
jupyterlab = "==4.0.8"
matplotlib = "==3.8.1"
openpyxl = "==3.1.2"
opentims_bruker_bridge = ""
pandas = "==2.0.3"
plotnine = "==0.12.4"
seaborn = "==0.13.0"
snakemake = "==7.32.4"
virtualenvwrapper = "==4.8.4"
absl-py = "==2.0.0"
agate = "==1.9.0"
agate-dbf = "==0.2.2"
agate-excel = "==0.3.0"
agate-sql = "==0.7.0"
anyio = "==4.0.0"
appdirs = "==1.4.4"
argon2-cffi = "==23.1.0"
argon2-cffi-bindings = "==21.2.0"
arrow = "==1.3.0"
asttokens = "==2.4.1"
astunparse = "==1.6.3"
async-lru = "==2.0.4"
attrs = "==23.1.0"
Babel = "==2.13.1"
beautifulsoup4 = "==4.12.2"
bleach = "==6.1.0"
blosc2 = "==2.2.9"
cachetools = "==5.3.2"
certifi = "==2023.7.22"
cffi = "==1.16.0"
charset-normalizer = "==3.3.2"
comm = "==0.1.4"
ConfigArgParse = "==1.7"
connection-pool = "==0.0.3"
contourpy = "==1.2.0"
cramjam = "==2.7.0"
cycler = "==0.12.1"
Cython = "==0.29.36"
datrie = "==0.8.2"
dbfread = "==2.0.7"
debugpy = "==1.8.0"
decorator = "==5.1.1"
defusedxml = "==0.7.1"
distlib = "==0.3.7"
docutils = "==0.20.1"
dpath = "==2.1.6"
duckdb = "==0.9.1"
et-xmlfile = "==1.1.0"
executing = "==2.0.1"
fastjsonschema = "==2.18.1"
fastparquet = "==2023.10.1"
filelock = "==3.13.1"
flatbuffers = "==23.5.26"
fonttools = "==4.44.0"
fqdn = "==1.5.1"
fsspec = "==2023.10.0"
gast = "==0.5.4"
gitdb = "==4.0.11"
GitPython = "==3.1.40"
google-auth = "==2.23.4"
google-auth-oauthlib = "==1.0.0"
google-pasta = "==0.2.0"
greenlet = "==3.0.1"
grpcio = "==1.59.2"
h5py = "==3.10.0"
hdbscan = "==0.8.33"
humanfriendly = "==10.0"
idna = "==3.4"
intervaltree = "==3.1.0"
ipywidgets = "==8.1.1"
isodate = "==0.6.1"
isoduration = "==20.11.0"
jedi = "==0.19.1"
Jinja2 = "==3.1.2"
joblib = "==1.3.2"
json5 = "==0.9.14"
jsonpointer = "==2.4"
jsonschema = "==4.19.2"
jsonschema-specifications = "==2023.7.1"
jupyter-console = "==6.6.3"
jupyter-events = "==0.8.0"
jupyter-lsp = "==2.2.0"
jupyter_client = "==8.5.0"
jupyter_core = "==5.5.0"
jupyter_server = "==2.9.1"
jupyter_server_terminals = "==0.4.4"
jupyterlab-pygments = "==0.2.2"
jupyterlab-widgets = "==3.0.9"
jupyterlab_server = "==2.25.0"
keras = "==2.14.0"
kiwisolver = "==1.4.5"
leather = "==0.3.4"
libclang = "==16.0.6"
llvmlite = "==0.41.1"
Markdown = "==3.5.1"
MarkupSafe = "==2.1.3"
matplotlib-inline = "==0.1.6"
methodtools = "==0.4.7"
mistune = "==3.0.2"
mizani = "==0.9.3"
ml-dtypes = "==0.2.0"
msgpack = "==1.0.7"
msgpack-numpy = "==0.4.8"
nbclient = "==0.8.0"
nbconvert = "==7.10.0"
nbformat = "==5.9.2"
ndindex = "==1.7"
nest-asyncio = "==1.5.8"
networkx = "==3.2.1"
notebook = "==7.0.6"
notebook_shim = "==0.2.3"
numba = "==0.58.1"
numexpr = "==2.8.7"
numpy = "==1.24.4"
oauthlib = "==3.2.2"
olefile = "==0.46"
opentims-bruker-bridge = "==1.1.0"
opt-einsum = "==3.3.0"
overrides = "==7.4.0"
packaging = "==23.2"
pandasql = "==0.7.3"
pandocfilters = "==1.5.0"
parsedatetime = "==2.6"
parso = "==0.8.3"
patsy = "==0.5.3"
pbr = "==5.11.1"
pexpect = "==4.8.0"
Pillow = "==10.1.0"
pip = "==23.3.1"
plac = "==1.4.1"
platformdirs = "==3.11.0"
polars = "==0.19.12"
prometheus-client = "==0.18.0"
prompt-toolkit = "==3.0.39"
protobuf = "==4.25.0"
psutil = "==5.9.6"
ptyprocess = "==0.7.0"
PuLP = "==2.7.0"
pure-eval = "==0.2.2"
py-cpuinfo = "==9.0.0"
py-expression-eval = "==0.3.14"
pyarrow = "==14.0.0"
pyasn1 = "==0.5.0"
pyasn1-modules = "==0.3.0"
pybind11 = "==2.11.1"
pycparser = "==2.21"
Pygments = "==2.16.1"
pyparsing = "==3.1.1"
PySocks = "==1.7.1"
python-dateutil = "==2.8.2"
python-json-logger = "==2.0.7"
python-prtree = "==0.6.0"
python-slugify = "==8.0.1"
pytimeparse = "==1.1.8"
pytz = "==2023.3.post1"
PyYAML = "==6.0.1"
pyzmq = "==25.1.1"
qtconsole = "==5.5.0"
QtPy = "==2.4.1"
referencing = "==0.30.2"
requests = "==2.31.0"
requests-oauthlib = "==1.3.1"
reretry = "==0.11.8"
rfc3339-validator = "==0.1.4"
rfc3986-validator = "==0.1.1"
rpds-py = "==0.12.0"
rsa = "==4.9"
scikit-learn = "==1.3.2"
scipy = "==1.11.3"
Send2Trash = "==1.8.2"
setproctitle = "==1.3.3"
setuptools = "==68.2.1"
six = "==1.16.0"
smart-open = "==6.4.0"
smmap = "==5.0.1"
sniffio = "==1.3.0"
sortedcontainers = "==2.4.0"
soupsieve = "==2.5"
SQLAlchemy = "==2.0.23"
stack-data = "==0.6.3"
statsmodels = "==0.14.0"
stevedore = "==5.1.0"
stopit = "==1.1.2"
tables = "==3.9.1"
tabulate = "==0.9.0"
tensorboard = "==2.14.1"
tensorboard-data-server = "==0.7.2"
tensorflow = "==2.14.0"
tensorflow-estimator = "==2.14.0"
tensorflow-io-gcs-filesystem = "==0.34.0"
termcolor = "==2.3.0"
terminado = "==0.17.1"
text-unidecode = "==1.3"
threadpoolctl = "==3.2.0"
throttler = "==1.2.2"
tinycss2 = "==1.2.1"
toml = "==0.10.2"
toposort = "==1.10"
tornado = "==6.3.3"
tqdm = "==4.66.1"
traitlets = "==5.13.0"
types-python-dateutil = "==2.8.19.14"
typing_extensions = "==4.8.0"
tzdata = "==2023.3"
uri-template = "==1.3.0"
urllib3 = "==2.0.7"
virtualenv = "==20.24.6"
virtualenv-clone = "==0.5.7"
wcwidth = "==0.2.9"
webcolors = "==1.13"
webencodings = "==0.5.1"
websocket-client = "==1.6.4"
Werkzeug = "==3.0.1"
wheel = "==0.41.2"
widgetsnbextension = "==4.0.9"
wirerope = "==0.4.7"
wrapt = "==1.14.1"
xgboost = "==2.0.1"
xlrd = "==2.0.1"
yte = "==1.5.1"
zstd = "==1.5.5.1"

[run]
default = "snakemake -call diagnostics/recalibration/G8027_cG8605_defaultconf.zip"
hela = "snakemake -call diagnostics/recalibration/G8602_cG8605_defaultconf.zip"
short = "snakemake -call diagnostics/recalibration/G0004_cG8605_defaultconf.zip"
thpr5p = "snakemake -call fragpipe/raw/rough_fragpipe_fullest_xgboost_tpr0.98/G8027_cNone_THPRScombined_d4_i4DFF_i4DFF"
test_5P_5DFF_SAGE_mz_recalibration = "snakemake -call outputs/doubleSageWithCheese/G8027/G8045"
test_HeLa_5DFF_SAGE_mz_recalibration = "snakemake -call outputs/doubleSageWithCheese/G8602/G8605"
self_calib_sage = "snakemake -call outputs/doubleSageWithCheese/G10303/G10303"
3ms1_full = "snakemake -call outputs/doubleSageWithCheese/G10297/G10303"
simple_5P = "snakemake -call outputs/simpleRun/G8027/G8045"
simple_HeLa = "snakemake -call outputs/simpleRun/G8602/G8605"
pure_HeLa = "snakemake -call outputs/optimizingMLedges/denoised_G8027/G8045/pureEdgeStats^naiveBayes^maxRank=10_notDepleted"
simple_3ms1 = "snakemake -call outputs/simpleRun/G10297/None"

[IGNORED_RUN_LOGS]
defcfg_path = "PosixPath('/home/matteo/MIDIA/midia_tester/midia_tester/configs/default.toml')"
full_commandline = "/home/matteo/.local/bin/midia_setup.py -o 2023_11_06_testing_recalibration"

[IGNORED_branches]
cached_opentims = "main"
ClusterMS = "main"
dia_common = "main"
kilograms = "main"
midia_cpp = "main"
midia_pipe = "main"
midia_search_engines = "main"
mmapped_df = "main"
MSclusterparser = "main"
opentims = "master"
pandas_ops = "main"
paramidiac = "main"
recapuccino = "main"
savetimspy = "main"

[freeze]

[IGNORED_RUN_LOGS.midia_setup_args]
outdir = "PosixPath('2023_11_06_testing_recalibration')"
force = false
pretend = false
