[git_versions]
midia_pipe="midiaID_november_rain_paper"
cached_opentims = "midiaID_november_rain_paper"
ClusterMS = "midiaID_november_rain_paper"
dia_common = "midiaID_november_rain_paper"
kilograms = "midiaID_november_rain_paper"
midia_schemes = "main"
midia_cpp = "midiaID_november_rain_paper"
midia_search_engines = "midiaID_november_rain_paper"
mmapped_df = "midiaID_november_rain_paper"
MSclusterparser = "midiaID_november_rain_paper"
opentims = "midiaID_november_rain_paper"
pandas_ops = "midiaID_november_rain_paper"
paramidiac = "midiaID_november_rain_paper"
paramidiac2 = "main"
recapuccino = "midiaID_november_rain_paper"
savetimspy = "midiaID_november_rain_paper"
snakemaketools = "main"
midia_fetcher = "main"
midia_pipe_hull = "main"

