[python]
pyversion = "python3.11"

[config]
test_param = false

[git_paths]
cached_opentims = "git+ssh://git@github.com/michalsta/cached_opentims.git"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
midia_schemes = "git+ssh://git@github.com/midiaIDorg/midia_schemes"
midia_cpp = "git+ssh://git@github.com/midiaIDorg/midia_cpp"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
opentims = "git+ssh://git@github.com/michalsta/opentims"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
paramidiac2 = "git+ssh://git@github.com/midiaIDorg/paramidiac2"
recapuccino = "git+ssh://git@github.com/midiaIDorg/recapuccino"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
snakemaketools = "git+ssh://git@github.com/midiaIDorg/snakemaketools"
midia_fetcher = "git+ssh://git@github.com/midiaIDorg/midia_fetcher"
midia_pipe_hull = "git+ssh://git@github.com/midiaIDorg/midia_pipe_hull"

[git_versions]
cached_opentims = "cc7222bded4014a2ccecbca28b0c0114f730a28c"
ClusterMS = "f95ed03765b284cea28bcc6371f2694f60cb5fe6"
dia_common = "e1d89b769ca262b3303311ead44efa30a9dd47e0"
kilograms = "707f195cb8efdf0730fb369d24fb5db6bf18c605"
midia_schemes = "f5b08abcf754a33f17b973830c9a5ea450b81034"
midia_cpp = "8bb217ae52babf363219d6d3d1bfc4bf0885f899"
midia_pipe = "d9de3aad6c7f35a06951d9b8efecde4aee821055"
midia_search_engines = "c6c5265f08824ff719b531d376056e310bec970c"
mmapped_df = "2ec952f59612b81a40ed6fdf9b337b72675ad58e"
MSclusterparser = "48243d702ebb1d77f50374815fbfca7c999bfa9b"
opentims = "4555b50915264da28d5a2e085def5462be01bdaa"
pandas_ops = "5a7d0a28a9e5f3facdc7869f87463323b89a9298"
paramidiac = "a82865d2f1935c3d074c8426d453a2a239143b93"
paramidiac2 = "83316516349c71a4ee4bef96f78a4915d36e7b3b"
py4DFF = "master"
recapuccino = "8efcf9a91ab2e24fc041633c0e5926b85d932103"
savetimspy = "e4bb81743ea8856084f9e056de7459ac9199ba58"
snakemaketools = "fbeb507e4f57962014bf726fc7cc45abf0fa9ddf"
midia_fetcher = "8690740dc588922bb6fb975d3bd434ef0fa8d039"
midia_pipe_hull = "a64ba1d6e95a286c1a5173020aeafd5b67a058aa"

[requirements_external]
virtualenvwrapper = "==6.1.0"
pyqt5 = ""
ipympl = "==0.9.4"
setuptools = "==65.6.3"
absl-py = "==2.1.0"
agate = "==1.11.0"
agate-dbf = "==0.2.3"
agate-excel = "==0.4.1"
agate-sql = "==0.7.2"
anyio = "==4.4.0"
appdirs = "==1.4.4"
argon2-cffi = "==23.1.0"
argon2-cffi-bindings = "==21.2.0"
argparse-dataclass = "==2.0.0"
arrow = "==1.3.0"
asttokens = "==2.4.1"
astunparse = "==1.6.3"
async-lru = "==2.0.4"
attrs = "==23.2.0"
Babel = "==2.15.0"
beautifulsoup4 = "==4.12.3"
bleach = "==6.1.0"
blosc2 = "==2.6.2"
boto3 = "==1.34.126"
botocore = "==1.34.126"
Brotli = "==1.1.0"
certifi = "==2024.6.2"
cffi = "==1.16.0"
charset-normalizer = "==3.3.2"
comm = "==0.2.2"
conda-inject = "==1.3.2"
ConfigArgParse = "==1.7"
connection-pool = "==0.0.3"
contourpy = "==1.2.1"
cowsay = "==6.1"
cramjam = "==2.8.3"
csvkit = "==2.0.0"
cycler = "==0.12.1"
Cython = "==3.0.10"
datrie = "==0.8.2"
dbfread = "==2.0.7"
debugpy = "==1.8.1"
decorator = "==5.1.1"
defusedxml = "==0.7.1"
distlib = "==0.3.8"
docutils = "==0.21.2"
dpath = "==2.2.0"
duckdb = "==1.0.0"
et-xmlfile = "==1.1.0"
executing = "==2.0.1"
fastjsonschema = "==2.19.1"
fastparquet = "==2024.5.0"
filelock = "==3.15.1"
flatbuffers = "==24.3.25"
fonttools = "==4.53.0"
fqdn = "==1.5.1"
fsspec = "==2024.6.0"
gast = "==0.5.4"
gitdb = "==4.0.11"
GitPython = "==3.1.43"
google-pasta = "==0.2.0"
greenlet = "==3.0.3"
grpcio = "==1.64.1"
h11 = "==0.14.0"
h5py = "==3.11.0"
httpcore = "==1.0.5"
httpx = "==0.27.0"
humanfriendly = "==10.0"
idna = "==3.7"
immutables = "==0.20"
iniconfig = "==2.0.0"
intervaltree = "==3.1.0"
ipykernel = "==6.29.4"
ipython = "==8.25.0"
ipython-genutils = "==0.2.0"
ipywidgets = "==8.1.3"
isodate = "==0.6.1"
isoduration = "==20.11.0"
jedi = "==0.19.1"
Jinja2 = "==3.1.4"
jmespath = "==1.0.1"
joblib = "==1.4.2"
json5 = "==0.9.25"
jsonpointer = "==3.0.0"
jsonschema = "==4.22.0"
jsonschema-specifications = "==2023.12.1"
jupyter = "==1.0.0"
jupyter-console = "==6.6.3"
jupyter-events = "==0.10.0"
jupyter-lsp = "==2.2.5"
jupyter_client = "==8.6.2"
jupyter_core = "==5.7.2"
jupyter_server = "==2.14.1"
jupyter_server_terminals = "==0.5.3"
jupyterlab = "==4.2.2"
jupyterlab_pygments = "==0.3.0"
jupyterlab_server = "==2.27.2"
jupyterlab_widgets = "==3.0.11"
keras = "==3.3.3"
kiwisolver = "==1.4.5"
leather = "==0.4.0"
libclang = "==18.1.1"
llvmlite = "==0.43.0"
Markdown = "==3.6"
markdown-it-py = "==3.0.0"
MarkupSafe = "==2.1.5"
matplotlib = "==3.9.0"
matplotlib-inline = "==0.1.7"
mdurl = "==0.1.2"
methodtools = "==0.4.7"
mistune = "==3.0.2"
mizani = "==0.11.4"
ml-dtypes = "==0.3.2"
msgpack = "==1.0.8"
msgpack-numpy = "==0.4.8"
namex = "==0.0.8"
nbclient = "==0.10.0"
nbconvert = "==7.16.4"
nbformat = "==5.10.4"
ndindex = "==1.8"
nest-asyncio = "==1.6.0"
networkx = "==3.3"
notebook = "==7.2.1"
notebook_shim = "==0.2.4"
numba = "==0.60.0"
numba-progress = "==1.1.0"
numexpr = "==2.10.0"
numpy = "==1.26.4"
olefile = "==0.47"
openpyxl = "==3.1.4"
opentims-bruker-bridge = "==1.1.0"
opt-einsum = "==3.3.0"
optree = "==0.11.0"
overrides = "==7.7.0"
packaging = "==24.1"
pandas = "==2.2.2"
pandasql = "==0.7.3"
pandocfilters = "==1.5.1"
parsedatetime = "==2.6"
parso = "==0.8.4"
patsy = "==0.5.6"
pbr = "==6.0.0"
pexpect = "==4.9.0"
pillow = "==10.3.0"
pip = "==24.0"
plac = "==1.4.3"
platformdirs = "==4.2.2"
plotly = "==5.22.0"
plotnine = "==0.13.6"
pluggy = "==1.5.0"
polars = "==0.20.31"
pony = "==0.7.17"
progressbar = "==2.5"
prometheus_client = "==0.20.0"
prompt_toolkit = "==3.0.47"
protobuf = "==4.25.3"
psutil = "==5.9.8"
ptyprocess = "==0.7.0"
PuLP = "==2.8.0"
pure-eval = "==0.2.2"
py-cpuinfo = "==9.0.0"
py-expression-eval = "==0.3.14"
pyarrow = "==16.1.0"
pybind11 = "==2.12.0"
pycparser = "==2.22"
Pygments = "==2.18.0"
PyMySQL = "==1.1.1"
pyparsing = "==3.1.2"
PyQt5 = "==5.15.10"
PyQt5-Qt5 = "==5.15.2"
PyQt5-sip = "==12.13.0"
pytest = "==8.2.2"
python-dateutil = "==2.9.0.post0"
python-json-logger = "==2.0.7"
python-slugify = "==8.0.4"
python_prtree = "==0.6.1"
pytimeparse = "==1.1.8"
pytz = "==2024.1"
PyYAML = "==6.0.1"
pyzmq = "==26.0.3"
qtconsole = "==5.5.2"
QtPy = "==2.4.1"
referencing = "==0.35.1"
requests = "==2.32.3"
reretry = "==0.11.8"
rfc3339-validator = "==0.1.4"
rfc3986-validator = "==0.1.1"
rich = "==13.7.1"
rpds-py = "==0.18.1"
s3transfer = "==0.10.1"
scikit-learn = "==1.5.0"
scipy = "==1.13.1"
seaborn = "==0.13.2"
Send2Trash = "==1.8.3"
setproctitle = "==1.3.3"
six = "==1.16.0"
smart-open = "==7.0.4"
smmap = "==5.0.1"
snakemake = "==8.14.0"
snakemake-interface-common = "==1.17.2"
snakemake-interface-executor-plugins = "==9.1.1"
snakemake-interface-report-plugins = "==1.0.0"
snakemake-interface-storage-plugins = "==3.2.2"
sniffio = "==1.3.1"
sortedcontainers = "==2.4.0"
soupsieve = "==2.5"
SQLAlchemy = "==2.0.30"
stack-data = "==0.6.3"
statsmodels = "==0.14.2"
stevedore = "==5.2.0"
stopit = "==1.1.2"
tables = "==3.9.2"
tabulate = "==0.9.0"
tenacity = "==8.3.0"
tensorboard = "==2.16.2"
tensorboard-data-server = "==0.7.2"
tensorflow = "==2.16.1"
tensorflow-io-gcs-filesystem = "==0.37.0"
termcolor = "==2.4.0"
terminado = "==0.18.1"
text-unidecode = "==1.3"
threadpoolctl = "==3.5.0"
throttler = "==1.2.2"
tinycss2 = "==1.3.0"
toml = "==0.10.2"
toposort = "==1.10"
tornado = "==6.4.1"
tqdm = "==4.66.4"
traitlets = "==5.14.3"
types-python-dateutil = "==2.9.0.20240316"
typing_extensions = "==4.12.2"
tzdata = "==2024.1"
UpSetPlot = "==0.9.0"
uri-template = "==1.3.0"
urllib3 = "==2.2.1"
virtualenv = "==20.26.2"
virtualenv-clone = "==0.5.7"
wcwidth = "==0.2.13"
webcolors = "==24.6.0"
webencodings = "==0.5.1"
websocket-client = "==1.8.0"
Werkzeug = "==3.0.3"
wheel = "==0.43.0"
widgetsnbextension = "==4.0.11"
wirerope = "==0.4.7"
wrapt = "==1.16.0"
xgboost = "==2.0.3"
xlrd = "==2.0.1"
yte = "==1.5.4"
zstd = "==1.5.5.1"

[snakemake_targets]
default = "out/base/default"
unfragmented = "out/base/default/dataset=G8605/calibration=G8605"
fiveP = "out/base/matteo"
HeLa = "out/base/matteo/dataset=G8602/calibration=G8605"
test = "out/base/{default,matteo}/{dataset=G8602/calibration=G8605,dataset=G8027/calibration=G8045}"
old = "-k out/base/old{,/dataset=G8602/calibration=G8605}"
immuno = "out/base/matteo/dataset=O13253/calibration=O13249/first_gen_search_engine_config=immuno/second_gen_search_engine_config=immuno"

[run]
default_old = "snakemake -call out/base/default"
fiveP_old = "snakemake -call out/base/_matteo"
HeLa_old = "snakemake -call out/base/_matteo/dataset=G8602/calibration=G8605"
HeLa_old_with_raw_cluster_stats = "snakemake -call out/base/_old/dataset=G8602/calibration=G8605/compare_raw_precursor_and_fragment_clusters=true"
test_old = "snakemake -call -k out/base/{default,_matteo}/{dataset=G8602/calibration=G8605,dataset=G8027/calibration=G8045}"
old_old = "snakemake -call -k out/base/_old{,/dataset=G8602/calibration=G8605}"
immuno_old = "snakemake -call out/base/_matteo/dataset=O13253/calibration=O13249/first_gen_search_engine_config=immuno_old/second_gen_search_engine_config=immuno_old"
old_no_calibration_all_old = "snakemake -k -call out/base/old/dataset={G8027,G8602}/calibration=none"
immuno_long = "snakemake -call out/base/{default,_old}/dataset=O13253/calibration=none/first_gen_search_engine_config=immuno_old/second_gen_search_engine_config=immuno_old"
regression_old = "snakemake -k -call out/base/default/{dataset=O11557/calibration=O11555,dataset=O11557/calibration=none,dataset=O11558/calibration=O11555,dataset=O11558/calibration=none}/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15/first_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/second_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=O11557/calibration=O11555,dataset=O11557/calibration=none,dataset=O11558/calibration=O11555,dataset=O11558/calibration=none}/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old/first_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/second_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/default/{dataset=G10271/calibration=G10262,dataset=G10271/calibration=none,dataset=B6230/calibration=B6231,dataset=B6230/calibration=none,dataset=B6699/calibration=B6688,dataset=B6699/calibration=none}/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15/first_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/second_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=G10271/calibration=G10262,dataset=G10271/calibration=none,dataset=B6230/calibration=B6231,dataset=B6230/calibration=none,dataset=B6699/calibration=B6688,dataset=B6699/calibration=none}/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old/first_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/second_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/default/{dataset=O12981/calibration=O12977,dataset=O12981/calibration=none}/first_gen_search_engine_config=phospho/second_gen_search_engine_config=phospho/first_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/second_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=O12981/calibration=O12977,dataset=O12981/calibration=none}/first_gen_search_engine_config=phospho_old/second_gen_search_engine_config=phospho_old/first_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/second_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/default/{dataset=B6613/calibration=B6610,dataset=B6613/calibration=none}/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15/first_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/second_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=B6613/calibration=B6610,dataset=B6613/calibration=none}/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old/first_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/second_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} -C global_temp_level=0.5"

[IGNORED_RUN_LOGS]
defcfg_path = "PosixPath('/home/matteo/MIDIA/midia_tester/midia_tester/configs/default.toml')"
full_commandline = "/home/matteo/MIDIA/venv_midia_tester/bin/midia_setup.py -o 2024_06_14_cordoba -r default"

[IGNORED_branches]
cached_opentims = "main"
ClusterMS = "main"
dia_common = "main"
kilograms = "main"
midia_schemes = "main"
midia_cpp = "main"
midia_pipe = "main"
midia_search_engines = "main"
mmapped_df = "main"
MSclusterparser = "main"
opentims = "master"
pandas_ops = "main"
paramidiac = "main"
paramidiac2 = "main"
recapuccino = "main"
savetimspy = "main"
snakemaketools = "main"
midia_fetcher = "main"
midia_pipe_hull = "main"

[freeze]

[IGNORED_RUN_LOGS.midia_setup_args]
outdir = "PosixPath('2024_06_14_cordoba')"
force = false
pretend = false
run = "default"
skip_self_checks = false
