[git_versions]
midia_pipe = "devel_december_seagull"
ClusterMS = "devel_december_seagull"
MSclusterparser = "devel_december_seagull"
cached_opentims = "devel_december_seagull"
dia_common = "devel_december_seagull"
kilograms = "main"
mgf_ops = "main"
midia_cpp = "main"
midia_fetcher = "main"
midia_pipe_hull = "main"
midia_schemes = "main"
midia_search_engines = "devel_december_seagull"
mmapped_df = "devel_december_seagull"
opentims = "devel_december_seagull"
pandas_ops = "main"
paramidiac = "devel_december_seagull"
paramidiac2 = "main"
recapuccino = "main"
savetimspy = "main"
snakemaketools = "main"

