[python]
pyversion = "python3.11"

[config]
test_param = false

[git_paths]
cached_opentims = "git+ssh://git@github.com/michalsta/cached_opentims.git"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
midia_schemes = "git+ssh://git@github.com/midiaIDorg/midia_schemes"
midia_cpp = "git+ssh://git@github.com/midiaIDorg/midia_cpp"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
opentims = "git+ssh://git@github.com/michalsta/opentims"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
paramidiac2 = "git+ssh://git@github.com/midiaIDorg/paramidiac2"
recapuccino = "git+ssh://git@github.com/midiaIDorg/recapuccino"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
snakemaketools = "git+ssh://git@github.com/midiaIDorg/snakemaketools"

[git_versions]
cached_opentims = "aea98c0c65ec20d6eed8c80eed2094bb8ce7c9ae"
ClusterMS = "de7be222d1040702c7565baaf79c4d3364d6623a"
dia_common = "f8cecbd653eb9379dee1ae41da46ed6e2cec578f"
kilograms = "8c29e4ceaecf2bd613d195e7b3af09eb3c0917d7"
midia_schemes = "75db466ff87910a6f8181dd5ff29f96999d33409"
midia_cpp = "8bb217ae52babf363219d6d3d1bfc4bf0885f899"
midia_pipe = "46d041f4df4fd9a74d8abb9460886543c55248ca"
midia_search_engines = "1c62b0c3d835417a2b15d8936f96f4fcde3e6799"
mmapped_df = "aff18ec23c348792829896e04464b5b4b5002fba"
MSclusterparser = "296d2360d81315f876e69a4b8b8ac8764d332c64"
opentims = "ce04915c91601a9c2fbfcdab880ed2e2a63360c3"
pandas_ops = "a3f6858dd36a4ed0964df50a6fb6a08a38ab2da5"
paramidiac = "a82865d2f1935c3d074c8426d453a2a239143b93"
paramidiac2 = "83316516349c71a4ee4bef96f78a4915d36e7b3b"
py4DFF = "master"
recapuccino = "8efcf9a91ab2e24fc041633c0e5926b85d932103"
savetimspy = "92f7d182a4c66b22c0c6fb97a6332940ff9c0859"
snakemaketools = "67fc07100b83bc9f507cd5e9726bb3cbb4ae6493"

[requirements_external]
csvkit = "==1.5.0"
gdown = "==5.1.0"
ipykernel = "==6.29.4"
ipython = "==8.23.0"
jupyter = "==1.0.0"
jupyterlab = "==4.1.6"
matplotlib = "==3.8.4"
mokapot = "==0.10.0"
openpyxl = "==3.1.2"
opentims_bruker_bridge = ""
pandas = "==2.2.1"
plotly = "==5.20.0"
plotnine = "==0.13.4"
pony = "==0.7.17"
pymysql = ""
pytest = "==8.1.1"
seaborn = "==0.13.2"
snakemake = "==8.10.6"
virtualenvwrapper = "==6.1.0"
pyqt5 = ""
ipympl = "==0.9.3"
cowsay = "==6.1"
absl-py = "==2.1.0"
agate = "==1.9.1"
agate-dbf = "==0.2.3"
agate-excel = "==0.4.1"
agate-sql = "==0.7.2"
anyio = "==4.3.0"
appdirs = "==1.4.4"
argon2-cffi = "==23.1.0"
argon2-cffi-bindings = "==21.2.0"
argparse-dataclass = "==2.0.0"
arrow = "==1.3.0"
asttokens = "==2.4.1"
astunparse = "==1.6.3"
async-lru = "==2.0.4"
attrs = "==23.2.0"
Babel = "==2.14.0"
beautifulsoup4 = "==4.12.3"
bleach = "==6.1.0"
blosc2 = "==2.6.2"
Brotli = "==1.1.0"
certifi = "==2024.2.2"
cffi = "==1.16.0"
charset-normalizer = "==3.3.2"
comm = "==0.2.2"
conda-inject = "==1.3.1"
ConfigArgParse = "==1.7"
connection-pool = "==0.0.3"
contourpy = "==1.2.1"
cramjam = "==2.8.3"
cycler = "==0.12.1"
datrie = "==0.8.2"
dbfread = "==2.0.7"
debugpy = "==1.8.1"
decorator = "==5.1.1"
defusedxml = "==0.7.1"
distlib = "==0.3.8"
docutils = "==0.21"
dpath = "==2.1.6"
duckdb = "==0.10.1"
et-xmlfile = "==1.1.0"
executing = "==2.0.1"
fastjsonschema = "==2.19.1"
fastparquet = "==2024.2.0"
filelock = "==3.13.4"
flatbuffers = "==24.3.25"
fonttools = "==4.51.0"
fqdn = "==1.5.1"
fsspec = "==2024.3.1"
gast = "==0.5.4"
gitdb = "==4.0.11"
GitPython = "==3.1.43"
google-pasta = "==0.2.0"
greenlet = "==3.0.3"
grpcio = "==1.62.1"
h11 = "==0.14.0"
h5py = "==3.11.0"
httpcore = "==1.0.5"
httpx = "==0.27.0"
humanfriendly = "==10.0"
idna = "==3.6"
immutables = "==0.20"
importlib_metadata = "==7.1.0"
iniconfig = "==2.0.0"
intervaltree = "==3.1.0"
ipython-genutils = "==0.2.0"
ipywidgets = "==8.1.2"
isodate = "==0.6.1"
isoduration = "==20.11.0"
jedi = "==0.19.1"
Jinja2 = "==3.1.3"
job-pool = "==0.2.6"
joblib = "==1.4.0"
json5 = "==0.9.24"
jsonpointer = "==2.4"
jsonschema = "==4.21.1"
jsonschema-specifications = "==2023.12.1"
jupyter-console = "==6.6.3"
jupyter-events = "==0.10.0"
jupyter-lsp = "==2.2.5"
jupyter_client = "==8.6.1"
jupyter_core = "==5.7.2"
jupyter_server = "==2.13.0"
jupyter_server_terminals = "==0.5.3"
jupyterlab_pygments = "==0.3.0"
jupyterlab_server = "==2.26.0"
jupyterlab_widgets = "==3.0.10"
keras = "==3.2.0"
kiwisolver = "==1.4.5"
leather = "==0.4.0"
libclang = "==18.1.1"
llvmlite = "==0.42.0"
lxml = "==5.2.1"
Markdown = "==3.6"
markdown-it-py = "==3.0.0"
MarkupSafe = "==2.1.5"
matplotlib-inline = "==0.1.6"
mdurl = "==0.1.2"
methodtools = "==0.4.7"
mistune = "==3.0.2"
mizani = "==0.11.1"
ml-dtypes = "==0.3.2"
msgpack = "==1.0.8"
msgpack-numpy = "==0.4.8"
namex = "==0.0.7"
nbclient = "==0.10.0"
nbconvert = "==7.16.3"
nbformat = "==5.10.4"
ndindex = "==1.8"
nest-asyncio = "==1.6.0"
networkx = "==3.3"
notebook = "==7.1.2"
notebook_shim = "==0.2.4"
numba = "==0.59.1"
numba-progress = "==1.1.0"
numexpr = "==2.10.0"
numpy = "==1.24.4"
olefile = "==0.47"
opentims-bruker-bridge = "==1.1.0"
opt-einsum = "==3.3.0"
optree = "==0.11.0"
overrides = "==7.7.0"
packaging = "==24.0"
pandasql = "==0.7.3"
pandocfilters = "==1.5.1"
parsedatetime = "==2.6"
parso = "==0.8.4"
patsy = "==0.5.6"
pbr = "==6.0.0"
pexpect = "==4.9.0"
pillow = "==10.3.0"
pip = "==24.0"
plac = "==1.4.3"
platformdirs = "==4.2.0"
pluggy = "==1.4.0"
polars = "==0.20.19"
progressbar = "==2.5"
prometheus_client = "==0.20.0"
prompt-toolkit = "==3.0.43"
protobuf = "==4.25.3"
psutil = "==5.9.8"
ptyprocess = "==0.7.0"
PuLP = "==2.8.0"
pure-eval = "==0.2.2"
py-cpuinfo = "==9.0.0"
py-expression-eval = "==0.3.14"
pyarrow = "==15.0.2"
pybind11 = "==2.12.0"
pycparser = "==2.22"
Pygments = "==2.17.2"
PyMySQL = "==1.1.0"
pyparsing = "==3.1.2"
PyQt5 = "==5.15.10"
PyQt5-Qt5 = "==5.15.2"
PyQt5-sip = "==12.13.0"
PySocks = "==1.7.1"
python-dateutil = "==2.9.0.post0"
python-json-logger = "==2.0.7"
python-prtree = "==0.6.0"
python-slugify = "==8.0.4"
pytimeparse = "==1.1.8"
pytz = "==2024.1"
PyYAML = "==6.0.1"
pyzmq = "==25.1.2"
qtconsole = "==5.5.1"
QtPy = "==2.4.1"
referencing = "==0.34.0"
requests = "==2.31.0"
reretry = "==0.11.8"
rfc3339-validator = "==0.1.4"
rfc3986-validator = "==0.1.1"
rich = "==13.7.1"
rpds-py = "==0.18.0"
scikit-learn = "==1.4.2"
scipy = "==1.13.0"
Send2Trash = "==1.8.3"
setproctitle = "==1.3.3"
setuptools = "==69.0.2"
six = "==1.16.0"
smart-open = "==7.0.4"
smmap = "==5.0.1"
snakemake-interface-common = "==1.17.1"
snakemake-interface-executor-plugins = "==9.1.0"
snakemake-interface-report-plugins = "==1.0.0"
snakemake-interface-storage-plugins = "==3.1.1"
sniffio = "==1.3.1"
sortedcontainers = "==2.4.0"
soupsieve = "==2.5"
SQLAlchemy = "==2.0.29"
stack-data = "==0.6.3"
statsmodels = "==0.14.1"
stevedore = "==5.2.0"
stopit = "==1.1.2"
tables = "==3.9.2"
tabulate = "==0.9.0"
tenacity = "==8.2.3"
tensorboard = "==2.16.2"
tensorboard-data-server = "==0.7.2"
tensorflow = "==2.16.1"
tensorflow-io-gcs-filesystem = "==0.36.0"
termcolor = "==2.4.0"
terminado = "==0.18.1"
text-unidecode = "==1.3"
threadpoolctl = "==3.4.0"
throttler = "==1.2.2"
tinycss2 = "==1.2.1"
toml = "==0.10.2"
toposort = "==1.10"
tornado = "==6.4"
tqdm = "==4.66.2"
traitlets = "==5.14.2"
triqler = "==0.7.3"
types-python-dateutil = "==2.9.0.20240316"
typing_extensions = "==4.11.0"
tzdata = "==2024.1"
uri-template = "==1.3.0"
urllib3 = "==2.2.1"
virtualenv = "==20.25.1"
virtualenv-clone = "==0.5.7"
wcwidth = "==0.2.13"
webcolors = "==1.13"
webencodings = "==0.5.1"
websocket-client = "==1.7.0"
Werkzeug = "==3.0.2"
wheel = "==0.42.0"
widgetsnbextension = "==4.0.10"
wirerope = "==0.4.7"
wrapt = "==1.16.0"
xgboost = "==2.0.3"
xlrd = "==2.0.1"
yte = "==1.5.4"
zipp = "==3.18.1"
zstd = "==1.5.5.1"

[run]
default = "snakemake -call diagnostics/recalibration/G8027_cG8605_defaultconf.zip"
hela = "snakemake -call diagnostics/recalibration/G8602_cG8605_defaultconf.zip"
short = "snakemake -call diagnostics/recalibration/G0004_cG8605_defaultconf.zip"
all5P = "snakemake -call outputs/all/G8027/G8045"
allhela = "snakemake -call outputs/all/G8602/G8605"
self_calib_sage = "snakemake -call outputs/all/G10303/G10303"
3ms1_full = "snakemake -call outputs/all/G10297/G10303"
simple_3ms1 = "snakemake -call outputs/all/G10297/None"
thpr5p = "snakemake -call fragpipe/raw/rough_fragpipe_fullest_xgboost_tpr0.98/G8027_cNone_THPRScombined_d4_i4DFF_i4DFF"
test_5P_5DFF_SAGE_mz_recalibration = "snakemake -call outputs/all/G8027/G8045"
test_HeLa_5DFF_SAGE_mz_recalibration = "snakemake -call outputs/all/G8602/G8605"
simple_5P = "snakemake -call outputs/all/G8027/G8045"
simple_HeLa = "snakemake -call outputs/all/G8602/G8605"
pure_HeLa = "snakemake -call outputs/optimizingMLedges/denoised_G8027/G8045/pureEdgeStats^naiveBayes^maxRank=10_notDepleted"

[IGNORED_RUN_LOGS]
defcfg_path = "PosixPath('/home/matteo/MIDIA/venv_midia_tester/lib/python3.10/site-packages/midia_tester/configs/default.toml')"
full_commandline = "/home/matteo/MIDIA/venv_midia_tester/bin/midia_setup.py -o 2024_04_10_malaga"

[IGNORED_branches]
cached_opentims = "main"
ClusterMS = "main"
dia_common = "main"
kilograms = "main"
midia_schemes = "main"
midia_cpp = "main"
midia_pipe = "main"
midia_search_engines = "main"
mmapped_df = "main"
MSclusterparser = "main"
opentims = "master"
pandas_ops = "main"
paramidiac = "main"
paramidiac2 = "main"
recapuccino = "main"
savetimspy = "main"
snakemaketools = "main"

[freeze]

[IGNORED_RUN_LOGS.midia_setup_args]
outdir = "PosixPath('2024_04_10_malaga')"
force = false
pretend = false
