[python]
pyversion = "python3.11"

[config]
test_param = false

[git_paths]
cached_opentims = "git+ssh://git@github.com/michalsta/cached_opentims.git"
ClusterMS = "git+ssh://git@github.com/midiaIDorg/ClusterMS"
dia_common = "git+ssh://git@github.com/midiaIDorg/dia_common"
kilograms = "git+ssh://git@github.com/midiaIDorg/kilograms"
mgf_ops = "git+ssh://git@github.com/midiaIDorg/mgf_ops"
midia_schemes = "git+ssh://git@github.com/midiaIDorg/midia_schemes"
midia_cpp = "git+ssh://git@github.com/midiaIDorg/midia_cpp"
midia_pipe = "git+ssh://git@github.com/midiaIDorg/midia_pipe"
midia_search_engines = "git+ssh://git@github.com/midiaIDorg/midia_search_engines"
mmapped_df = "git+ssh://git@github.com/michalsta/mmapped_df"
MSclusterparser = "git+ssh://git@github.com/midiaIDorg/MSclusterparser"
opentims = "git+ssh://git@github.com/michalsta/opentims"
pandas_ops = "git+ssh://git@github.com/midiaIDorg/pandas_ops"
paramidiac = "git+ssh://git@github.com/midiaIDorg/paramidiac"
paramidiac2 = "git+ssh://git@github.com/midiaIDorg/paramidiac2"
recapuccino = "git+ssh://git@github.com/midiaIDorg/recapuccino"
savetimspy = "git+ssh://git@github.com/midiaIDorg/savetimspy"
snakemaketools = "git+ssh://git@github.com/midiaIDorg/snakemaketools"
midia_fetcher = "git+ssh://git@github.com/midiaIDorg/midia_fetcher"
midia_pipe_hull = "git+ssh://git@github.com/midiaIDorg/midia_pipe_hull"

[git_versions]
cached_opentims = "midiaID_november_rain_paper"
ClusterMS = "midiaID_november_rain_paper"
dia_common = "midiaID_november_rain_paper"
kilograms = "main"
mgf_ops = "midiaID_november_rain_paper"
midia_cpp = "main"
midia_pipe = "bugfix_interactive_pip"
midia_schemes = "main"
midia_search_engines = "midiaID_november_rain_paper"
mmapped_df = "midiaID_november_rain_paper"
MSclusterparser = "main"
opentims = "midiaID_november_rain_paper"
pandas_ops = "midiaID_november_rain_paper"
paramidiac = "midiaID_november_rain_paper"
paramidiac2 = "midiaID_november_rain_paper"
recapuccino = "midiaID_november_rain_paper"
savetimspy="main"
snakemaketools = "main"
midia_fetcher = "main"
midia_pipe_hull = "midiaID_november_rain_paper"

[requirements_external]
ms2rescore = "==3.1.3"
im2deep = "==0.2.0"
deeplcretrainer = "==1.0.0"
keras = "==3.6.0"
ms2rescore-rs = "==0.4.0"
protobuf = "==5.28.3"
psm = "-utils==1.1.1"
pyarrow = "==18.0.0"
pydantic = "==2.9.2"
pydantic_core = "==2.23.4"
python = "-utils==3.9.0"
rfc3986 = "-validator==0.1.1"
wrapt = "==1.16.0"

[snakemake_targets]
default = "out/base/default"
unfragmented = "out/base/default/dataset=G8605/calibration=G8605"
fiveP = "out/base/matteo"
HeLa = "out/base/matteo/dataset=G8602/calibration=G8605"
test = "out/base/{default,matteo}/{dataset=G8602/calibration=G8605,dataset=G8027/calibration=G8045}"
old = "-k out/base/old{,/dataset=G8602/calibration=G8605}"
immuno = "out/base/matteo/dataset=O13253/calibration=O13249/first_gen_search_engine_config=immuno/second_gen_search_engine_config=immuno"

[run]
default_old = "snakemake -call out/base/default"
fiveP_old = "snakemake -call out/base/_matteo"
HeLa_old = "snakemake -call out/base/_matteo/dataset=G8602/calibration=G8605"
HeLa_old_with_raw_cluster_stats = "snakemake -call out/base/_old/dataset=G8602/calibration=G8605/compare_raw_precursor_and_fragment_clusters=true"
test_old = "snakemake -call -k out/base/{default,_matteo}/{dataset=G8602/calibration=G8605,dataset=G8027/calibration=G8045}"
old_old = "snakemake -call -k out/base/_old{,/dataset=G8602/calibration=G8605}"
immuno_old = "snakemake -call out/base/_matteo/dataset=O13253/calibration=O13249/first_gen_search_engine_config=immuno_old/second_gen_search_engine_config=immuno_old"
old_no_calibration_all_old = "snakemake -k -call out/base/old/dataset={G8027,G8602}/calibration=none"
immuno_long = "snakemake -call out/base/{default,_old}/dataset=O13253/calibration=none/first_gen_search_engine_config=immuno_old/second_gen_search_engine_config=immuno_old"
regression_old = "snakemake -k -call out/base/default/{dataset=O11557/calibration=O11555,dataset=O11557/calibration=none,dataset=O11558/calibration=O11555,dataset=O11558/calibration=none}/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15/first_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/second_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=O11557/calibration=O11555,dataset=O11557/calibration=none,dataset=O11558/calibration=O11555,dataset=O11558/calibration=none}/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old/first_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/second_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/default/{dataset=G10271/calibration=G10262,dataset=G10271/calibration=none,dataset=B6230/calibration=B6231,dataset=B6230/calibration=none,dataset=B6699/calibration=B6688,dataset=B6699/calibration=none}/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15/first_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/second_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=G10271/calibration=G10262,dataset=G10271/calibration=none,dataset=B6230/calibration=B6231,dataset=B6230/calibration=none,dataset=B6699/calibration=B6688,dataset=B6699/calibration=none}/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old/first_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/second_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/default/{dataset=O12981/calibration=O12977,dataset=O12981/calibration=none}/first_gen_search_engine_config=phospho/second_gen_search_engine_config=phospho/first_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/second_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=O12981/calibration=O12977,dataset=O12981/calibration=none}/first_gen_search_engine_config=phospho_old/second_gen_search_engine_config=phospho_old/first_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/second_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/default/{dataset=B6613/calibration=B6610,dataset=B6613/calibration=none}/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15/first_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/second_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} out/base/_old/{dataset=B6613/calibration=B6610,dataset=B6613/calibration=none}/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old/first_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/second_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq4,_maxRankLeq6,_maxRankLeq8,_maxScoreLeq85Quantile,_maxScoreLeq90Quantile,_maxScoreLeq95Quantile} -C global_temp_level=0.5"
small_regression_1 = "out/base/{_old/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old,default/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15}/{dataset=O11557,dataset=O11558}/calibration=none/first_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/second_gen_fasta=HYE_2024_02_16_6066entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq6,_maxRankLeq12,_ms2_norm_score_geq_q10} out/base/{_old/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old,default/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15}/{dataset=G10271,dataset=B6230,dataset=B6699}/calibration=none/first_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/second_gen_fasta=Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq6,_maxRankLeq12,_ms2_norm_score_geq_q10}"
small_regression_2 = "out/base/{_old/first_gen_search_engine_config=phospho_old/second_gen_search_engine_config=phospho_old,default/first_gen_search_engine_config=phospho/second_gen_search_engine_config=phospho}/dataset=O12981/calibration=none/first_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/second_gen_fasta=Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq6,_maxRankLeq12,_ms2_norm_score_geq_q10} out/base/{_old/first_gen_search_engine_config=p12f15_old/second_gen_search_engine_config=p12f15_old,default/first_gen_search_engine_config=p12f15/second_gen_search_engine_config=p12f15}/dataset=B6613/calibration=none/first_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/second_gen_fasta=Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/edge_refinement_config={_maxRankLeq6,_maxRankLeq12,_ms2_norm_score_geq_q10}"
