[git_versions]
midia_pipe = "devel_december_seagull"
ClusterMS = "devel_december_seagull"
MSclusterparser = "devel_december_seagull"
cached_opentims = "devel_december_seagull"
dia_common = "devel_december_seagull"
kilograms = "main"
mgf_ops = "main"
midia_cpp = "main"
midia_fetcher = "main"
midia_pipe_hull = "main"
midia_schemes = "main"
midia_search_engines = "devel_december_seagull"
mmapped_df = "devel_december_seagull"
opentims = "devel_december_seagull"
pandas_ops = "main"
paramidiac = "devel_december_seagull"
paramidiac2 = "main"
recapuccino = "main"
savetimspy = "main"
snakemaketools = "main"

[run]
regression_1 = "snakemake -call -k outputs/regression/O11557/O11555/HYE_2024_02_16_6066entries_contaminant_tenzer/HYE_2024_02_16_6066entries_contaminant_tenzer/p12f15_1psm/p12f15_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted outputs/regression/O11558/O11555/HYE_2024_02_16_6066entries_contaminant_tenzer/HYE_2024_02_16_6066entries_contaminant_tenzer/p12f15_1psm/p12f15_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted outputs/regression/G10271/G10262/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/p12f15_1psm/p12f15_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted outputs/regression/O12981/O12977/Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/Mouse_2024_02_16_UniProt_Taxon10090_Reviewed_17208entries_contaminant_tenzer/phospho_1psm/phospho_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted outputs/regression/{F9462/F9459,F9463/F9460,F9464/F9461}/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/p12f15_1psm/p12f15_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted"
regression_2 = "snakemake -call -k outputs/regression/{O13253/O13249,O13271/O13267}/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/immuno_mhc2_1psm/immuno_mhc2_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted outputs/regression/O12787/O12784/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/immuno_mhc2_1psm/immuno_mhc2_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted outputs/regression/{B6230/B6231,B6699/B6688}/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/Human_2024_02_16_UniProt_Taxon9606_Reviewed_20434entries_contaminant_tenzer/p12f15_1psm/p12f15_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted outputs/regression/B6613/B6610/Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/Yeast_2024_02_16_UniProt_Taxon643680_5984entries_contaminant_tenzer/p12f15_1psm/p12f15_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted"
test = "snakemake -call -k outputs/regression/O11557/O11555/HYE_2024_02_16_6066entries_contaminant_tenzer/HYE_2024_02_16_6066entries_contaminant_tenzer/p12f15_1psm/p12f15_1psm/baseEdgeStats^positiveEllipse^maxRank=12_depleted"
